import type { TemplateChannel, TemplateTone, TemplateStructure } from '@/types/communicationTemplate';

export interface LibraryTemplateField {
  name: string;
  type: 'Text' | 'List' | 'Number' | 'Date' | 'Select';
  description?: string;
}

export type LibraryCategory = 'geral' | 'vendas' | 'sucesso' | 'produto' | 'marketing' | 'recrutamento';

export interface LibraryTemplate {
  id: string;
  name: string;
  description: string;
  category: LibraryCategory;
  channel: TemplateChannel;
  tone: TemplateTone;
  structureType: TemplateStructure;
  fields: LibraryTemplateField[];
  body: string;
  subject?: string;
}

export const LIBRARY_CATEGORIES: { id: LibraryCategory; label: string; icon: string; color: string }[] = [
  { id: 'geral', label: 'Geral', icon: 'LayoutGrid', color: 'bg-slate-500' },
  { id: 'vendas', label: 'Vendas', icon: 'TrendingUp', color: 'bg-blue-500' },
  { id: 'sucesso', label: 'Sucesso', icon: 'Heart', color: 'bg-green-500' },
  { id: 'produto', label: 'Produto', icon: 'Package', color: 'bg-purple-500' },
  { id: 'marketing', label: 'Marketing', icon: 'Megaphone', color: 'bg-orange-500' },
  { id: 'recrutamento', label: 'Recrutamento', icon: 'Users', color: 'bg-pink-500' },
];

export const CATEGORY_LABELS: Record<LibraryCategory, string> = {
  geral: 'Geral',
  vendas: 'Vendas',
  sucesso: 'Sucesso',
  produto: 'Produto',
  marketing: 'Marketing',
  recrutamento: 'Recrutamento',
};

export const LIBRARY_TEMPLATES: LibraryTemplate[] = [
  // ── Geral ──
  {
    id: 'lib-boas-vindas',
    name: 'Boas-vindas',
    description: 'Mensagem de boas-vindas para novos contactos ou clientes',
    category: 'geral',
    channel: 'email',
    tone: 'human',
    structureType: 'AIDA',
    fields: [
      { name: 'Saudação', type: 'Text', description: 'Mensagem inicial de boas-vindas personalizada com o nome do contacto.' },
      { name: 'Apresentação', type: 'Text', description: 'Breve apresentação da empresa e do valor que oferece ao novo cliente.' },
      { name: 'Próximos Passos', type: 'List', description: 'Lista de ações recomendadas para o cliente começar a utilizar o serviço.' },
    ],
    subject: 'Bem-vindo(a), {{primeiro_nome}}! 🎉',
    body: '**Atenção**\nOlá {{primeiro_nome}}, é um prazer tê-lo connosco!\n\n**Interesse**\nA nossa equipa está pronta para ajudá-lo a alcançar os seus objetivos.\n\n**Desejo**\nDescubra tudo o que preparámos para si.\n\n**Ação**\nResponda a este email para agendarmos uma conversa inicial.',
  },
  {
    id: 'lib-agradecimento',
    name: 'Agradecimento',
    description: 'Template para agradecer reuniões, compras ou interações',
    category: 'geral',
    channel: 'email',
    tone: 'human',
    structureType: 'custom',
    fields: [
      { name: 'Contexto', type: 'Text', description: 'Contexto da interação anterior — reunião, compra ou outra atividade relevante.' },
      { name: 'Agradecimento', type: 'Text', description: 'Mensagem de agradecimento genuína pelo tempo e disponibilidade do contacto.' },
      { name: 'Próximo Passo', type: 'Text', description: 'Definir claramente a próxima ação esperada ou compromisso assumido.' },
    ],
    subject: 'Obrigado, {{primeiro_nome}}!',
    body: 'Olá {{primeiro_nome}},\n\nMuito obrigado pela sua disponibilidade. Foi uma conversa muito produtiva.\n\nComo combinado, envio em anexo o resumo dos pontos discutidos.\n\nQualquer dúvida, estou à disposição.\n\nCumprimentos,\n{{responsavel_nome}}',
  },
  {
    id: 'lib-confirmacao',
    name: 'Confirmação',
    description: 'Confirmar agendamentos, pedidos ou ações',
    category: 'geral',
    channel: 'whatsapp',
    tone: 'professional',
    structureType: 'custom',
    fields: [
      { name: 'Evento', type: 'Text', description: 'Tipo de evento a confirmar — reunião, consulta, entrega ou outro.' },
      { name: 'Data', type: 'Date', description: 'Data e hora confirmada para o evento agendado.' },
      { name: 'Detalhes', type: 'Text', description: 'Informações adicionais como local, link de videochamada ou instruções.' },
    ],
    body: 'Olá {{primeiro_nome}} 👋\n\nConfirmamos o seu agendamento para o dia {{data_ultima_sessao}}.\n\nCaso precise remarcar, responda a esta mensagem.\n\nAté breve!',
  },

  // ── Vendas ──
  {
    id: 'lib-bant',
    name: 'BANT Qualification',
    description: 'Framework de qualificação com Budget, Authority, Need e Timeline',
    category: 'vendas',
    channel: 'email',
    tone: 'professional',
    structureType: 'AIDA',
    fields: [
      { name: 'Budget', type: 'Text', description: 'Resumir discussões sobre orçamento, preocupações com preço ou disposição para investir.' },
      { name: 'Authority', type: 'Text', description: 'Identificar os decisores-chave, o seu papel no processo de compra e influenciadores internos.' },
      { name: 'Need', type: 'List', description: 'Listar as necessidades e desafios principais que a empresa pretende resolver.' },
      { name: 'Timeline', type: 'Text', description: 'Definir o cronograma ideal para tomada de decisão e implementação.' },
    ],
    subject: '{{company_name}} — Próximos passos para {{primeiro_nome}}',
    body: '**Atenção**\nOlá {{primeiro_nome}}, obrigado pelo interesse em conhecer as nossas soluções.\n\n**Interesse**\nPara garantirmos que conseguimos entregar o máximo valor à {{company_name}}, gostaria de entender melhor:\n\n- Qual o orçamento previsto para este projeto?\n- Quem mais participa na decisão?\n- Quais os principais desafios que pretendem resolver?\n- Qual o timeline ideal para implementação?\n\n**Desejo**\nEmpresas como a sua conseguiram reduzir custos em 30% nos primeiros 3 meses.\n\n**Ação**\nPodemos agendar 20 minutos esta semana?',
  },
  {
    id: 'lib-cold-outreach',
    name: 'Cold Outreach',
    description: 'Primeiro contacto frio com lead qualificado',
    category: 'vendas',
    channel: 'email',
    tone: 'commercial',
    structureType: 'ColdOutreach',
    fields: [
      { name: 'Hook', type: 'Text', description: 'Abertura personalizada que capta atenção com referência ao setor ou empresa do lead.' },
      { name: 'Credibilidade', type: 'Text', description: 'Prova social ou caso de sucesso que demonstra resultados concretos.' },
      { name: 'Proposta', type: 'Text', description: 'Proposta de valor clara e concisa do que a solução pode fazer pelo lead.' },
      { name: 'CTA', type: 'Text', description: 'Chamada para ação simples e de baixo compromisso — ex.: chamada de 15 minutos.' },
    ],
    subject: '{{primeiro_nome}}, uma ideia para a {{company_name}}',
    body: '**Hook**\nOlá {{primeiro_nome}}, reparei que a {{company_name}} está a crescer no setor de {{industry}}.\n\n**Credibilidade**\nAjudámos empresas similares a aumentar a sua conversão em 45%.\n\n**Proposta**\nGostaria de partilhar como podemos replicar esses resultados consigo.\n\n**CTA**\nTem 15 minutos esta semana para uma chamada rápida?',
  },
  {
    id: 'lib-followup-vendas',
    name: 'Follow-Up Comercial',
    description: 'Seguimento após proposta ou reunião comercial',
    category: 'vendas',
    channel: 'email',
    tone: 'professional',
    structureType: 'FollowUp',
    fields: [
      { name: 'Contexto', type: 'Text', description: 'Referenciar a conversa ou proposta anterior para manter continuidade.' },
      { name: 'Valor', type: 'Text', description: 'Reforçar o valor estimado e o retorno que a solução pode gerar.' },
      { name: 'Próximo Passo', type: 'Text', description: 'Sugerir data e formato para a próxima interação comercial.' },
    ],
    subject: 'Re: Proposta para {{company_name}}',
    body: '**Contexto**\n{{primeiro_nome}}, espero que esteja tudo bem. Voltando à nossa conversa da semana passada.\n\n**Valor**\nGostaria de reforçar que a nossa solução pode gerar um retorno estimado de {{potential_value}}€.\n\n**Próximo Passo**\nPodemos avançar para a fase de demonstração? Sugiro terça ou quinta às 10h.',
  },
  {
    id: 'lib-proposta',
    name: 'Envio de Proposta',
    description: 'Email formal com envio de proposta comercial',
    category: 'vendas',
    channel: 'email',
    tone: 'professional',
    structureType: 'BAB',
    fields: [
      { name: 'Situação Atual', type: 'Text', description: 'Descrever a situação atual do cliente e os desafios que enfrenta.' },
      { name: 'Resultado', type: 'Text', description: 'Pintar o cenário ideal após adotar a solução proposta.' },
      { name: 'Proposta', type: 'Text', description: 'Detalhar a proposta comercial e como faz a ponte entre o atual e o desejado.' },
      { name: 'Condições', type: 'List', description: 'Listar condições especiais, prazos de validade e termos da proposta.' },
    ],
    subject: 'Proposta Comercial — {{company_name}}',
    body: '**Before**\nAtualmente, a {{company_name}} enfrenta desafios na gestão de {{industry}}.\n\n**After**\nCom a nossa solução, poderá automatizar processos e ganhar eficiência.\n\n**Bridge**\nEm anexo, encontra a proposta detalhada com condições especiais válidas até ao final do mês.\n\n**Ação**\nFicamos a aguardar o seu feedback. Qualquer dúvida, estou disponível.',
  },
  {
    id: 'lib-spin-selling',
    name: 'SPIN Selling',
    description: 'Framework de perguntas estratégicas para descoberta de necessidades',
    category: 'vendas',
    channel: 'email',
    tone: 'professional',
    structureType: 'custom',
    fields: [
      { name: 'Situação', type: 'Text', description: 'Perguntas para compreender o contexto atual do prospect — ferramentas, processos e equipa.' },
      { name: 'Problema', type: 'Text', description: 'Identificar dificuldades, frustrações e ineficiências no cenário atual.' },
      { name: 'Implicação', type: 'List', description: 'Explorar as consequências de não resolver os problemas — impacto financeiro, operacional e estratégico.' },
      { name: 'Necessidade-Payoff', type: 'Text', description: 'Conduzir o prospect a verbalizar os benefícios da solução e o valor percebido.' },
    ],
    subject: 'Descoberta — {{company_name}} × {{product_name}}',
    body: '**Situação**\n{{primeiro_nome}}, gostaria de perceber como gerem atualmente {{industry}}.\n\n**Problema**\nQuais os maiores desafios que enfrentam nesta área?\n\n**Implicação**\nSe estes desafios persistirem, que impacto terão nos resultados do próximo trimestre?\n\n**Necessidade-Payoff**\nSe conseguissem resolver isto, que ganhos estimam obter?',
  },
  {
    id: 'lib-meddic',
    name: 'MEDDIC Qualification',
    description: 'Qualificação enterprise com métricas, decisores e champion',
    category: 'vendas',
    channel: 'email',
    tone: 'professional',
    structureType: 'custom',
    fields: [
      { name: 'Métricas', type: 'List', description: 'KPIs e métricas quantificáveis que o prospect usa para medir sucesso.' },
      { name: 'Economic Buyer', type: 'Text', description: 'Identificar quem tem autoridade final para aprovar o orçamento.' },
      { name: 'Critérios de Decisão', type: 'List', description: 'Requisitos técnicos, funcionais e comerciais que guiam a escolha.' },
      { name: 'Processo de Decisão', type: 'Text', description: 'Etapas, stakeholders e timeline do processo interno de compra.' },
      { name: 'Identificar Dor', type: 'Text', description: 'A dor principal que motiva a procura de uma solução — urgência e impacto.' },
      { name: 'Champion', type: 'Text', description: 'O aliado interno que defende a solução e influencia a decisão.' },
    ],
    subject: 'Qualificação — {{company_name}}',
    body: '**Métricas**\nQuais KPIs são mais relevantes para medir o sucesso em {{industry}}?\n\n**Economic Buyer**\nQuem será o responsável pela aprovação final deste investimento?\n\n**Critérios de Decisão**\nQue critérios a equipa usará para avaliar as opções?\n\n**Processo de Decisão**\nComo funciona o processo interno de aprovação?\n\n**Identificar Dor**\nQual é o problema mais urgente que precisam resolver?\n\n**Champion**\nQuem na equipa seria o maior defensor desta mudança?',
  },
  {
    id: 'lib-challenger-sale',
    name: 'Challenger Sale',
    description: 'Ensinar, personalizar e assumir controlo da conversa comercial',
    category: 'vendas',
    channel: 'email',
    tone: 'commercial',
    structureType: 'custom',
    fields: [
      { name: 'Teach', type: 'Text', description: 'Insight ou perspetiva nova que desafia a visão atual do prospect sobre o mercado.' },
      { name: 'Tailor', type: 'Text', description: 'Personalizar a mensagem ao contexto específico da empresa, setor e desafios.' },
      { name: 'Take Control', type: 'Text', description: 'Conduzir a conversa para o próximo passo concreto com assertividade.' },
    ],
    subject: '{{primeiro_nome}}, uma perspetiva diferente sobre {{industry}}',
    body: '**Teach**\n{{primeiro_nome}}, a maioria das empresas em {{industry}} assume que o maior desafio é X — mas os dados mostram que Y tem 3× mais impacto no resultado final.\n\n**Tailor**\nPara a {{company_name}}, isto é particularmente relevante porque o vosso modelo depende de eficiência operacional.\n\n**Take Control**\nSugiro uma sessão de 20 minutos na quarta-feira para mostrar como empresas similares já resolveram isto. Funciona às 14h?',
  },
  {
    id: 'lib-champ',
    name: 'ChAMP',
    description: 'Qualificação começando pelos desafios do cliente',
    category: 'vendas',
    channel: 'email',
    tone: 'professional',
    structureType: 'custom',
    fields: [
      { name: 'Challenges', type: 'Text', description: 'Os desafios prioritários que o prospect enfrenta e quer resolver.' },
      { name: 'Authority', type: 'List', description: 'Mapear os decisores, influenciadores e o processo de aprovação.' },
      { name: 'Money', type: 'Text', description: 'Enquadramento orçamental — budget disponível, ROI esperado e modelo de pricing.' },
      { name: 'Prioritization', type: 'List', description: 'Nível de prioridade do projeto face a outras iniciativas internas.' },
    ],
    subject: 'Desafios em {{industry}} — {{company_name}}',
    body: '**Challenges**\n{{primeiro_nome}}, quais são os principais desafios que a {{company_name}} enfrenta em {{industry}} neste momento?\n\n**Authority**\nQuem mais estaria envolvido na decisão de adotar uma nova solução?\n\n**Money**\nJá têm orçamento alocado para resolver este tipo de problema?\n\n**Prioritization**\nComo posicionam este projeto em relação a outras prioridades do trimestre?',
  },
  {
    id: 'lib-gpctbaci',
    name: 'GPCTBA/C&I',
    description: 'Framework completo de qualificação com objetivos, planos e consequências',
    category: 'vendas',
    channel: 'email',
    tone: 'professional',
    structureType: 'custom',
    fields: [
      { name: 'Goals', type: 'Text', description: 'Objetivos de negócio de curto e longo prazo que o prospect quer alcançar.' },
      { name: 'Plans', type: 'Text', description: 'Planos e estratégias atuais para atingir esses objetivos.' },
      { name: 'Challenges', type: 'List', description: 'Obstáculos que impedem a execução dos planos atuais.' },
      { name: 'Timeline', type: 'Text', description: 'Prazo previsto para implementar a solução e ver resultados.' },
      { name: 'Budget', type: 'Number', description: 'Orçamento disponível ou faixa de investimento prevista.' },
      { name: 'Authority', type: 'Text', description: 'Decisor final e cadeia de aprovação para este tipo de investimento.' },
      { name: 'Consequences', type: 'Text', description: 'O que acontece se o problema não for resolvido — impacto negativo no negócio.' },
      { name: 'Implications', type: 'Text', description: 'Benefícios positivos e oportunidades que surgem ao resolver o problema.' },
    ],
    subject: 'Qualificação Completa — {{company_name}}',
    body: '**Goals**\nQuais são os principais objetivos de {{company_name}} para os próximos 12 meses?\n\n**Plans**\nQue planos têm em curso para atingir esses objetivos?\n\n**Challenges**\nQuais obstáculos estão a dificultar a execução?\n\n**Timeline**\nQuando precisam ter isto resolvido?\n\n**Budget**\nJá definiram um intervalo de investimento para esta iniciativa?\n\n**Authority**\nQuem dará a aprovação final?\n\n**Consequences**\nO que acontece se não resolverem isto a tempo?\n\n**Implications**\nQue oportunidades se abrem quando resolverem?',
  },
  {
    id: 'lib-sandler-pain',
    name: 'Sandler Pain Funnel',
    description: 'Funil de dor para descobrir a motivação real de compra',
    category: 'vendas',
    channel: 'email',
    tone: 'human',
    structureType: 'PAS',
    fields: [
      { name: 'Dor Superficial', type: 'Text', description: 'O sintoma inicial que o prospect menciona — a razão aparente para procurar ajuda.' },
      { name: 'Impacto no Negócio', type: 'Text', description: 'Como essa dor afeta os resultados da empresa — custos, receita perdida, ineficiência.' },
      { name: 'Impacto Pessoal', type: 'Text', description: 'Como o problema afeta pessoalmente o decisor — stress, reputação, objetivos de carreira.' },
      { name: 'Compromisso', type: 'Text', description: 'Validar a disposição do prospect para investir tempo e recursos na resolução.' },
    ],
    subject: 'Resolver {{pain_point}} — {{company_name}}',
    body: '**Problem**\n{{primeiro_nome}}, mencionou que {{pain_point}} tem sido um desafio para a {{company_name}}.\n\n**Agitate**\nSe isto continuar, qual o impacto estimado nos resultados do próximo trimestre? E como é que isso afeta a sua equipa no dia a dia?\n\n**Solve**\nTemos ajudado empresas como a vossa a resolver isto em menos de 30 dias. Gostaria de ver como? Posso mostrar-lhe num call de 15 minutos.',
  },

  // ── Sucesso ──
  {
    id: 'lib-onboarding',
    name: 'Onboarding Cliente',
    description: 'Guia de início para novos clientes',
    category: 'sucesso',
    channel: 'email',
    tone: 'human',
    structureType: 'AIDA',
    fields: [
      { name: 'Boas-vindas', type: 'Text', description: 'Mensagem de boas-vindas entusiasta para o novo cliente.' },
      { name: 'Passos Iniciais', type: 'List', description: 'Lista sequencial dos primeiros passos para configuração e início de uso.' },
      { name: 'Recursos', type: 'List', description: 'Links e materiais de apoio — tutoriais, FAQ, vídeos de introdução.' },
      { name: 'Suporte', type: 'Text', description: 'Informação de contacto da equipa de suporte e disponibilidade.' },
    ],
    subject: '🚀 Vamos começar, {{primeiro_nome}}!',
    body: '**Atenção**\nBem-vindo(a) a bordo, {{primeiro_nome}}! Estamos entusiasmados por tê-lo connosco.\n\n**Interesse**\nPara tirar o máximo partido, preparámos um guia rápido:\n1. Configure o seu perfil\n2. Explore o dashboard\n3. Agende a sua sessão de onboarding\n\n**Desejo**\nOs nossos clientes atingem resultados nos primeiros 14 dias.\n\n**Ação**\nClique aqui para começar a sua configuração.',
  },
  {
    id: 'lib-checkin',
    name: 'Check-in Periódico',
    description: 'Ponto de situação regular com o cliente',
    category: 'sucesso',
    channel: 'email',
    tone: 'empathetic',
    structureType: 'FollowUp',
    fields: [
      { name: 'Saudação', type: 'Text', description: 'Saudação personalizada referenciando o tempo desde o último contacto.' },
      { name: 'Progresso', type: 'Text', description: 'Resumo do progresso do cliente e métricas relevantes desde a última interação.' },
      { name: 'Próximos Passos', type: 'List', description: 'Sugestões de próximas ações para maximizar resultados.' },
    ],
    subject: 'Como está a correr, {{primeiro_nome}}?',
    body: '**Contexto**\nOlá {{primeiro_nome}}, passaram {{days_since_last_contact}} dias desde o nosso último contacto.\n\n**Valor**\nGostaria de saber como está a correr a sua experiência e se há algo que possamos melhorar.\n\n**Próximo Passo**\nTem disponibilidade para uma chamada rápida de 10 minutos esta semana?',
  },
  {
    id: 'lib-satisfacao',
    name: 'Pesquisa de Satisfação',
    description: 'Solicitar feedback e NPS do cliente',
    category: 'sucesso',
    channel: 'email',
    tone: 'human',
    structureType: 'PAS',
    fields: [
      { name: 'Pedido', type: 'Text', description: 'Pedido gentil de feedback explicando a importância da opinião do cliente.' },
      { name: 'Formulário', type: 'Text', description: 'Link e instruções para o formulário de satisfação ou NPS.' },
      { name: 'Incentivo', type: 'Text', description: 'Incentivo para completar o formulário — desconto, conteúdo exclusivo, etc.' },
    ],
    subject: '{{primeiro_nome}}, a sua opinião é importante 💬',
    body: '**Problema**\nQueremos garantir que está a ter a melhor experiência possível.\n\n**Agitação**\nO seu feedback é essencial para continuarmos a evoluir.\n\n**Solução**\nPreencha este formulário rápido (2 minutos) e ajude-nos a melhorar.\n\n**Ação**\n[Link para formulário]',
  },

  // ── Produto ──
  {
    id: 'lib-lancamento',
    name: 'Lançamento de Produto',
    description: 'Anunciar novo produto ou funcionalidade',
    category: 'produto',
    channel: 'email',
    tone: 'commercial',
    structureType: 'AIDA',
    fields: [
      { name: 'Produto', type: 'Text', description: 'Nome e breve descrição do novo produto ou funcionalidade lançada.' },
      { name: 'Benefícios', type: 'List', description: 'Lista dos principais benefícios e diferenciais do novo produto.' },
      { name: 'Disponibilidade', type: 'Date', description: 'Data de disponibilidade e como aceder ao novo produto.' },
      { name: 'Preço', type: 'Number', description: 'Informação de preços, planos e condições de lançamento.' },
    ],
    subject: '🆕 Novo: Conheça o {{produto_nome}}',
    body: '**Atenção**\n{{primeiro_nome}}, temos uma novidade especial para si!\n\n**Interesse**\nApresentamos o {{produto_nome}} — desenhado para resolver os seus maiores desafios.\n\n**Desejo**\nPrincipais benefícios:\n- Mais produtividade\n- Interface intuitiva\n- Integração completa\n\n**Ação**\nExperimente gratuitamente durante 14 dias.',
  },
  {
    id: 'lib-demo',
    name: 'Convite para Demo',
    description: 'Convidar lead para demonstração do produto',
    category: 'produto',
    channel: 'email',
    tone: 'professional',
    structureType: 'ColdOutreach',
    fields: [
      { name: 'Produto', type: 'Text', description: 'Produto ou solução que será demonstrada na sessão.' },
      { name: 'Benefício', type: 'Text', description: 'Benefício principal que o lead vai descobrir durante a demonstração.' },
      { name: 'Duração', type: 'Text', description: 'Duração estimada da demo e o que será coberto.' },
      { name: 'Horários', type: 'List', description: 'Opções de horários disponíveis para agendamento.' },
    ],
    subject: 'Demo personalizada para {{company_name}}',
    body: '**Hook**\nOlá {{primeiro_nome}}, preparámos uma demonstração personalizada para a {{company_name}}.\n\n**Credibilidade**\nEm 30 minutos, mostramos como empresas do setor {{industry}} estão a usar a nossa plataforma.\n\n**Proposta**\nA demo é gratuita e sem compromisso.\n\n**CTA**\nEscolha o melhor horário: [link de agendamento]',
  },
  {
    id: 'lib-feature-update',
    name: 'Feature Update',
    description: 'Informar sobre atualização de funcionalidade',
    category: 'produto',
    channel: 'email',
    tone: 'human',
    structureType: 'custom',
    fields: [
      { name: 'Feature', type: 'Text', description: 'Nome e contexto da funcionalidade atualizada ou nova.' },
      { name: 'O que muda', type: 'List', description: 'Lista detalhada das alterações, melhorias e novos comportamentos.' },
      { name: 'Como usar', type: 'Text', description: 'Instruções simples sobre como ativar e usar a nova funcionalidade.' },
    ],
    subject: '✨ Nova atualização disponível',
    body: 'Olá {{primeiro_nome}},\n\nAcabámos de lançar uma atualização importante:\n\n🔹 Novo dashboard de analytics\n🔹 Exportação avançada de dados\n🔹 Integração com calendários\n\nJá está disponível na sua conta. Explore agora!\n\nQualquer dúvida, a nossa equipa está disponível.',
  },

  // ── Marketing ──
  {
    id: 'lib-newsletter',
    name: 'Newsletter',
    description: 'Newsletter periódica com conteúdos e novidades',
    category: 'marketing',
    channel: 'email',
    tone: 'human',
    structureType: 'custom',
    fields: [
      { name: 'Destaque', type: 'Text', description: 'Artigo ou notícia principal em destaque nesta edição.' },
      { name: 'Artigos', type: 'List', description: 'Lista curada de artigos, posts ou recursos relevantes para o leitor.' },
      { name: 'Eventos', type: 'List', description: 'Próximos eventos, webinars ou datas importantes.' },
      { name: 'CTA', type: 'Text', description: 'Chamada para ação principal — ex.: partilhar, subscrever ou participar.' },
    ],
    subject: '📬 Newsletter {{empresa_nome}} — Edição de hoje',
    body: 'Olá {{primeiro_nome}},\n\nAqui está o resumo da semana:\n\n📰 Destaque: [Título do artigo principal]\n\n📚 Artigos:\n- [Artigo 1]\n- [Artigo 2]\n- [Artigo 3]\n\n📅 Próximos Eventos:\n- [Evento 1]\n- [Evento 2]\n\nBoa leitura!\nEquipa {{empresa_nome}}',
  },
  {
    id: 'lib-promocao',
    name: 'Promoção',
    description: 'Campanha promocional com oferta especial',
    category: 'marketing',
    channel: 'email',
    tone: 'commercial',
    structureType: 'FourP',
    fields: [
      { name: 'Oferta', type: 'Text', description: 'Descrição atrativa da oferta ou promoção em curso.' },
      { name: 'Desconto', type: 'Number', description: 'Percentagem ou valor do desconto oferecido.' },
      { name: 'Validade', type: 'Date', description: 'Data limite para aproveitar a promoção — criar urgência.' },
      { name: 'Condições', type: 'Text', description: 'Termos, condições e restrições aplicáveis à oferta.' },
    ],
    subject: '🔥 Oferta exclusiva para si, {{primeiro_nome}}!',
    body: '**Picture**\nImagine ter acesso a todas as funcionalidades premium a um preço especial.\n\n**Promise**\nDurante esta semana, oferecemos 30% de desconto no plano anual.\n\n**Proof**\nMais de 500 empresas já aproveitaram esta oferta no último trimestre.\n\n**Push**\nAproveite agora — válido até sexta-feira.',
  },
  {
    id: 'lib-reativacao',
    name: 'Reativação',
    description: 'Reengajar leads ou clientes inativos',
    category: 'marketing',
    channel: 'email',
    tone: 'empathetic',
    structureType: 'REENGAGE',
    fields: [
      { name: 'Referência', type: 'Text', description: 'Referência ao último contacto ou interação com o cliente inativo.' },
      { name: 'Novidade', type: 'Text', description: 'Novidades e melhorias relevantes desde o último contacto.' },
      { name: 'Incentivo', type: 'Text', description: 'Oferta especial ou incentivo para motivar o regresso do cliente.' },
    ],
    subject: 'Sentimos a sua falta, {{primeiro_nome}} 💙',
    body: '**Referência**\nOlá {{primeiro_nome}}, há algum tempo que não nos falamos.\n\n**Atualização**\nDesde a última vez, lançámos várias melhorias que acredito serem relevantes para si.\n\n**Oportunidade**\nGostaria de oferecer-lhe um mês gratuito para explorar as novidades.\n\n**Ação**\nInteressado? Responda a este email e tratamos de tudo.',
  },

  // ── Recrutamento ──
  {
    id: 'lib-entrevista',
    name: 'Convite para Entrevista',
    description: 'Convidar candidato para entrevista',
    category: 'recrutamento',
    channel: 'email',
    tone: 'professional',
    structureType: 'custom',
    fields: [
      { name: 'Cargo', type: 'Text', description: 'Título e departamento da posição para a qual o candidato é convidado.' },
      { name: 'Data', type: 'Date', description: 'Data e hora propostas para a entrevista.' },
      { name: 'Local', type: 'Text', description: 'Endereço físico ou link de videochamada para a entrevista.' },
      { name: 'Entrevistador', type: 'Text', description: 'Nome e cargo da pessoa que conduzirá a entrevista.' },
    ],
    subject: 'Convite para Entrevista — {{company_name}}',
    body: 'Olá {{primeiro_nome}},\n\nObrigado pelo seu interesse na posição na {{company_name}}.\n\nGostaríamos de convidá-lo(a) para uma entrevista:\n\n📅 Data: [data]\n📍 Local: [local/link videochamada]\n👤 Com: {{responsavel_nome}}\n\nPor favor, confirme a sua disponibilidade respondendo a este email.\n\nCumprimentos,\n{{responsavel_nome}}',
  },
  {
    id: 'lib-oferta',
    name: 'Oferta de Emprego',
    description: 'Proposta formal de contratação',
    category: 'recrutamento',
    channel: 'email',
    tone: 'professional',
    structureType: 'custom',
    fields: [
      { name: 'Cargo', type: 'Text', description: 'Título oficial da posição oferecida e responsabilidades principais.' },
      { name: 'Salário', type: 'Number', description: 'Remuneração bruta anual ou mensal proposta ao candidato.' },
      { name: 'Benefícios', type: 'List', description: 'Lista completa de benefícios — seguro, férias, formação, bónus, etc.' },
      { name: 'Data Início', type: 'Date', description: 'Data prevista para início de funções.' },
    ],
    subject: '🎉 Proposta de Emprego — {{company_name}}',
    body: 'Olá {{primeiro_nome}},\n\nTemos o prazer de lhe apresentar uma proposta formal para a posição na {{company_name}}.\n\nDetalhes da oferta:\n- Cargo: [cargo]\n- Remuneração: [valor]\n- Benefícios: [lista]\n- Data de início prevista: [data]\n\nFicamos a aguardar a sua resposta até [prazo].\n\nCom entusiasmo,\n{{responsavel_nome}}',
  },
];
