import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface InviteRequest {
  invites: Array<{ email: string; name: string; message?: string }>;
  workspaceId: string;
  domain: string;
}

const handler = async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!RESEND_API_KEY) throw new Error("RESEND_API_KEY not configured");

    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
      { auth: { autoRefreshToken: false, persistSession: false } }
    );

    // Get auth user from JWT
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("Authorization required");
    
    const token = authHeader.replace("Bearer ", "");
    const { data: { user }, error: authError } = await supabaseAdmin.auth.getUser(token);
    if (authError || !user) throw new Error("Unauthorized");

    const { invites, workspaceId, domain }: InviteRequest = await req.json();

    if (!invites?.length || !workspaceId || !domain) {
      throw new Error("invites, workspaceId e domain são obrigatórios");
    }

    // Get workspace info for branding
    const { data: workspace } = await supabaseAdmin
      .from("workspaces")
      .select("name, slug")
      .eq("id", workspaceId)
      .single();

    if (!workspace) throw new Error("Workspace não encontrado");

    const results: Array<{ email: string; success: boolean; error?: string }> = [];

    for (const invite of invites) {
      try {
        // Insert invite record (token is auto-generated by DB default)
        const { data: inviteRecord, error: insertError } = await supabaseAdmin
          .from("c2c_seller_invites")
          .insert({
            workspace_id: workspaceId,
            email: invite.email,
            name: invite.name,
            message: invite.message || null,
            invited_by: user.id,
          })
          .select("invite_token")
          .single();

        if (insertError) {
          results.push({ email: invite.email, success: false, error: insertError.message });
          continue;
        }

        const inviteUrl = `${domain}/c2c/${workspace.slug}/invite/${inviteRecord.invite_token}`;

        // Send email via Resend
        const emailRes = await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${RESEND_API_KEY}`,
          },
          body: JSON.stringify({
            from: "Marketplace <onboarding@resend.dev>",
            to: [invite.email],
            subject: `Convite para vender no ${workspace.name}`,
            html: `
              <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
                <h1 style="color: #333; font-size: 24px;">Olá ${invite.name}! 👋</h1>
                <p style="color: #555; font-size: 16px; line-height: 1.6;">
                  Foste convidado(a) a vender no marketplace <strong>${workspace.name}</strong>.
                </p>
                ${invite.message ? `
                  <div style="background: #f5f5f5; border-radius: 8px; padding: 16px; margin: 16px 0;">
                    <p style="color: #555; font-size: 14px; margin: 0; font-style: italic;">"${invite.message}"</p>
                  </div>
                ` : ""}
                <h3 style="color: #333; font-size: 18px;">Porquê vender connosco?</h3>
                <ul style="color: #555; font-size: 14px; line-height: 1.8;">
                  <li>✅ Comissões competitivas</li>
                  <li>📈 Visibilidade para milhares de compradores</li>
                  <li>🛠️ Ferramentas profissionais de venda</li>
                  <li>💬 Chat direto com compradores</li>
                  <li>📊 Painel de analytics e performance</li>
                </ul>
                <div style="text-align: center; margin: 32px 0;">
                  <a href="${inviteUrl}" style="background: #2563eb; color: white; padding: 14px 32px; border-radius: 8px; text-decoration: none; font-weight: bold; font-size: 16px; display: inline-block;">
                    Ativar Conta de Vendedor
                  </a>
                </div>
                <p style="color: #999; font-size: 12px; text-align: center;">
                  Este convite expira em 7 dias. Se não reconheces este convite, podes ignorar este email.
                </p>
              </div>
            `,
          }),
        });

        if (!emailRes.ok) {
          const errBody = await emailRes.text();
          console.error("Resend error:", errBody);
          results.push({ email: invite.email, success: false, error: "Erro ao enviar email" });
        } else {
          results.push({ email: invite.email, success: true });
        }
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : "Erro desconhecido";
        results.push({ email: invite.email, success: false, error: msg });
      }
    }

    return new Response(JSON.stringify({ success: true, results }), {
      status: 200,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  } catch (error: unknown) {
    console.error("Error in send-c2c-seller-invite:", error);
    const message = error instanceof Error ? error.message : "Erro desconhecido";
    return new Response(JSON.stringify({ success: false, error: message }), {
      status: 500,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  }
};

serve(handler);
