import { useState, useEffect } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  Tag,
  Sparkles,
  Plus,
  X,
  Check,
  Loader2,
  Info,
} from "lucide-react";
import { cn } from "@/lib/utils";
import {
  AVAILABLE_TAGS,
  ConversationTag,
  useAutoTags,
  useUpdateConversationTags,
  ConversationTagContext,
} from "@/hooks/useAutoTags";
import { Message } from "@/hooks/useMessages";
import { Conversation } from "@/hooks/useConversations";

interface ConversationAutoTagsProps {
  conversation: Conversation;
  messages: Message[];
  className?: string;
}

const tagColors: Record<string, string> = {
  "Lead": "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400 border-blue-200 dark:border-blue-800",
  "Cliente": "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400 border-green-200 dark:border-green-800",
  "Oportunidade Aberta": "bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-400 border-purple-200 dark:border-purple-800",
  "Suporte": "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400 border-amber-200 dark:border-amber-800",
  "Financeiro": "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-400 border-emerald-200 dark:border-emerald-800",
  "Alta Intenção": "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400 border-red-200 dark:border-red-800",
  "Baixa Prioridade": "bg-gray-100 text-gray-800 dark:bg-gray-900/30 dark:text-gray-400 border-gray-200 dark:border-gray-800",
  "Negociação": "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-400 border-orange-200 dark:border-orange-800",
  "Proposta Enviada": "bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-400 border-indigo-200 dark:border-indigo-800",
  "Reclamação": "bg-rose-100 text-rose-800 dark:bg-rose-900/30 dark:text-rose-400 border-rose-200 dark:border-rose-800",
  "Parceria": "bg-cyan-100 text-cyan-800 dark:bg-cyan-900/30 dark:text-cyan-400 border-cyan-200 dark:border-cyan-800",
  "Indicação": "bg-teal-100 text-teal-800 dark:bg-teal-900/30 dark:text-teal-400 border-teal-200 dark:border-teal-800",
};

export function ConversationAutoTags({
  conversation,
  messages,
  className,
}: ConversationAutoTagsProps) {
  const [showEditor, setShowEditor] = useState(false);
  const [selectedTags, setSelectedTags] = useState<string[]>([]);
  const [reasoning, setReasoning] = useState<string | null>(null);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const { generateTags, isLoading: isGenerating } = useAutoTags();
  const updateTags = useUpdateConversationTags();

  // Get current tags (user tags take precedence over AI tags)
  const aiTags = (conversation as any).ai_tags || [];
  const userTags = (conversation as any).user_tags || [];
  const currentTags: string[] = userTags.length > 0 ? userTags : aiTags;
  const isAutoAssigned = (conversation as any).tags_auto_assigned && userTags.length === 0;

  useEffect(() => {
    setSelectedTags(currentTags);
  }, [JSON.stringify(currentTags)]);

  // Auto-generate tags if none exist and we have messages
  useEffect(() => {
    if (
      !hasAutoGenerated &&
      currentTags.length === 0 &&
      messages.length >= 3 &&
      !(conversation as any).tags_auto_assigned
    ) {
      handleAutoGenerate();
      setHasAutoGenerated(true);
    }
  }, [messages.length, currentTags.length, hasAutoGenerated]);

  const handleAutoGenerate = async () => {
    const context: ConversationTagContext = {
      channel: conversation.channel,
      leadStatus: conversation.lead?.status,
      hasOpportunity: (conversation.opportunities?.length || 0) > 0,
      opportunityValue: conversation.opportunities?.[0]?.value || undefined,
      aiIntent: conversation.ai_intent || undefined,
      aiPriority: conversation.ai_priority || undefined,
      aiSentiment: conversation.ai_sentiment || undefined,
    };

    const result = await generateTags(messages, context, conversation.id);
    if (result) {
      setSelectedTags(result.tags);
      setReasoning(result.reasoning);
    }
  };

  const toggleTag = (tag: string) => {
    setSelectedTags((prev) =>
      prev.includes(tag) ? prev.filter((t) => t !== tag) : [...prev, tag].slice(0, 4)
    );
  };

  const handleSave = () => {
    updateTags.mutate({
      conversationId: conversation.id,
      tags: selectedTags,
      isUserOverride: true,
    });
    setShowEditor(false);
  };

  if (messages.length < 2) return null;

  return (
    <div className={cn("space-y-1", className)}>
      {/* Tags display */}
      <div className="flex items-center gap-1.5 flex-wrap">
        {currentTags.length > 0 ? (
          <>
            {currentTags.map((tag) => (
              <Badge
                key={tag}
                variant="outline"
                className={cn(
                  "text-xs py-0 h-5 gap-1 cursor-pointer hover:opacity-80 transition-opacity",
                  tagColors[tag] || "bg-muted"
                )}
                onClick={() => setShowEditor(true)}
              >
                {tag}
              </Badge>
            ))}
          </>
        ) : (
          <Button
            variant="ghost"
            size="sm"
            className="h-6 text-xs text-muted-foreground gap-1"
            onClick={handleAutoGenerate}
            disabled={isGenerating}
          >
            {isGenerating ? (
              <Loader2 className="w-3 h-3 animate-spin" />
            ) : (
              <Sparkles className="w-3 h-3" />
            )}
            Gerar tags
          </Button>
        )}

        {/* Edit button */}
        {currentTags.length > 0 && (
          <Popover open={showEditor} onOpenChange={setShowEditor}>
            <PopoverTrigger asChild>
              <Button variant="ghost" size="sm" className="h-5 w-5 p-0">
                <Plus className="w-3 h-3" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-72 p-3" align="start">
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Editar tags</span>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-6 text-xs gap-1"
                    onClick={handleAutoGenerate}
                    disabled={isGenerating}
                  >
                    {isGenerating ? (
                      <Loader2 className="w-3 h-3 animate-spin" />
                    ) : (
                      <Sparkles className="w-3 h-3" />
                    )}
                    IA
                  </Button>
                </div>

                <div className="flex flex-wrap gap-1.5">
                  {AVAILABLE_TAGS.map((tag) => (
                    <Badge
                      key={tag}
                      variant="outline"
                      className={cn(
                        "text-xs py-0.5 cursor-pointer transition-all",
                        selectedTags.includes(tag)
                          ? tagColors[tag]
                          : "bg-muted/50 text-muted-foreground hover:bg-muted"
                      )}
                      onClick={() => toggleTag(tag)}
                    >
                      {selectedTags.includes(tag) && <Check className="w-3 h-3 mr-1" />}
                      {tag}
                    </Badge>
                  ))}
                </div>

                {reasoning && (
                  <div className="flex items-start gap-2 p-2 bg-muted/50 rounded text-xs">
                    <Info className="w-3 h-3 mt-0.5 flex-shrink-0 text-muted-foreground" />
                    <p className="text-muted-foreground">{reasoning}</p>
                  </div>
                )}

                <div className="flex justify-end gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setShowEditor(false)}
                  >
                    Cancelar
                  </Button>
                  <Button
                    size="sm"
                    onClick={handleSave}
                    disabled={updateTags.isPending}
                  >
                    {updateTags.isPending ? (
                      <Loader2 className="w-4 h-4 animate-spin" />
                    ) : (
                      "Salvar"
                    )}
                  </Button>
                </div>
              </div>
            </PopoverContent>
          </Popover>
        )}
      </div>

      {/* Auto-assigned microcopy */}
      {isAutoAssigned && currentTags.length > 0 && (
        <div className="flex items-center gap-1 text-xs text-muted-foreground">
          <Sparkles className="w-3 h-3" />
          <span>Tags atribuídas automaticamente</span>
        </div>
      )}
    </div>
  );
}
