export type FeatureStatus = "active" | "beta" | "planned";
export type ModuleCategory = "Core" | "CRM" | "Comunicação" | "Vendas" | "Marketing" | "Loja Online" | "Portal B2B" | "Comunidade" | "IA" | "Estratégia" | "Vertical" | "Admin";
export type PlanTier = "free" | "basic" | "pro" | "agency";

export interface Feature {
  name: string;
  description: string;
  status: FeatureStatus;
  aiPowered: boolean;
}

export interface ModulePage {
  name: string;
  route: string;
}

export interface FeatureModule {
  id: string;
  name: string;
  category: ModuleCategory;
  description: string;
  minPlan: PlanTier;
  status: FeatureStatus;
  moduleSlug: string | null;
  pages: ModulePage[];
  hooks: string[];
  edgeFunctions: string[];
  tables: string[];
  features: Feature[];
  dependencies: string[];
}

export const MODULE_CATEGORIES: { id: ModuleCategory; label: string; color: string }[] = [
  { id: "Core", label: "Core", color: "bg-slate-500" },
  { id: "CRM", label: "CRM", color: "bg-blue-500" },
  { id: "Comunicação", label: "Comunicação", color: "bg-indigo-500" },
  { id: "Vendas", label: "Vendas", color: "bg-green-500" },
  { id: "Marketing", label: "Marketing", color: "bg-pink-500" },
  { id: "Loja Online", label: "Loja Online", color: "bg-orange-500" },
  { id: "Portal B2B", label: "Portal B2B", color: "bg-cyan-500" },
  { id: "Comunidade", label: "Comunidade", color: "bg-violet-500" },
  { id: "IA", label: "IA", color: "bg-purple-500" },
  { id: "Estratégia", label: "Estratégia", color: "bg-amber-500" },
  { id: "Vertical", label: "Vertical", color: "bg-teal-500" },
  { id: "Admin", label: "Admin", color: "bg-red-500" },
];

export const FEATURE_REGISTRY: FeatureModule[] = [
  // ══════════ CORE ══════════
  {
    id: "core-dashboard",
    name: "Dashboard",
    category: "Core",
    description: "Painel principal com KPIs, widgets e layout personalizável",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Dashboard", route: "/dashboard" }],
    hooks: ["useDashboardWidgets", "useDashboardStats"],
    edgeFunctions: ["ai-dashboard-insights"],
    tables: ["dashboard_widgets", "dashboard_layouts"],
    features: [
      { name: "KPIs em tempo real", description: "Indicadores de performance actualizados automaticamente", status: "active", aiPowered: false },
      { name: "Widgets personalizáveis", description: "Adicionar e reorganizar widgets no dashboard", status: "active", aiPowered: false },
      { name: "Insights IA", description: "Sugestões inteligentes baseadas nos dados do workspace", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "core-feed",
    name: "Mural Interno",
    category: "Core",
    description: "Feed de comunicação interna entre membros do workspace",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Feed", route: "/dashboard/feed" }],
    hooks: ["useFeedPosts", "useFeedReactions"],
    edgeFunctions: [],
    tables: ["feed_posts", "feed_reactions", "feed_comments"],
    features: [
      { name: "Publicar posts", description: "Partilhar actualizações com a equipa", status: "active", aiPowered: false },
      { name: "Reacções", description: "Reagir a publicações com emojis", status: "active", aiPowered: false },
      { name: "Comentários", description: "Comentar em publicações da equipa", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "core-productivity",
    name: "Produtividade",
    category: "Core",
    description: "Gestão de tarefas e prioridades diárias com coach IA",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Tarefas", route: "/dashboard/tasks" }],
    hooks: ["useTasks", "useProductivityCoach"],
    edgeFunctions: ["productivity-coach"],
    tables: ["tasks", "task_assignments"],
    features: [
      { name: "Criar tarefas", description: "Adicionar e gerir tarefas da equipa", status: "active", aiPowered: false },
      { name: "Prioridades diárias", description: "Definir e acompanhar prioridades do dia", status: "active", aiPowered: false },
      { name: "Coach IA", description: "Sugestões inteligentes de produtividade", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "core-calendar",
    name: "Calendário",
    category: "Core",
    description: "Gestão de eventos, disponibilidade e reuniões vídeo",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Calendário", route: "/dashboard/calendar" },
      { name: "Disponibilidade", route: "/dashboard/calendar/availability" },
      { name: "Booking Público", route: "/booking/:slug" },
    ],
    hooks: ["useCalendarEvents", "useMeetings", "useAvailability"],
    edgeFunctions: ["create-video-meeting", "booking-router"],
    tables: ["calendar_events", "meetings", "availability_slots", "booking_pages"],
    features: [
      { name: "Eventos", description: "Criar e gerir eventos no calendário", status: "active", aiPowered: false },
      { name: "Reuniões vídeo", description: "Criar salas de reunião com link partilhável", status: "active", aiPowered: false },
      { name: "Disponibilidade", description: "Definir horários disponíveis para booking", status: "active", aiPowered: false },
      { name: "Booking público", description: "Página pública para marcações", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "core-imports",
    name: "Importações",
    category: "Core",
    description: "Importação em massa via CSV com mapeamento de campos",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Importações", route: "/dashboard/imports" }],
    hooks: ["useImportHistory", "useCSVImport"],
    edgeFunctions: [],
    tables: ["import_history", "import_mappings"],
    features: [
      { name: "Import CSV", description: "Importar dados em massa via ficheiro CSV", status: "active", aiPowered: false },
      { name: "Mapeamento de campos", description: "Mapear colunas do CSV para campos do sistema", status: "active", aiPowered: false },
      { name: "Histórico", description: "Ver histórico de importações anteriores", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "core-forms",
    name: "Formulários",
    category: "Core",
    description: "Builder de formulários com submissões e geração IA",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Formulários", route: "/dashboard/forms" },
      { name: "Formulário Público", route: "/f/:slug" },
    ],
    hooks: ["useForms", "useFormSubmissions"],
    edgeFunctions: ["generate-form-schema", "generate-smart-form", "process-form-submission"],
    tables: ["forms", "form_fields", "form_submissions"],
    features: [
      { name: "Form builder", description: "Construir formulários com drag & drop", status: "active", aiPowered: false },
      { name: "Gerar com IA", description: "Gerar formulários automaticamente com IA", status: "active", aiPowered: true },
      { name: "Submissões", description: "Ver e gerir submissões recebidas", status: "active", aiPowered: false },
      { name: "Formulários públicos", description: "Publicar formulários com link partilhável", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "core-custom-fields",
    name: "Campos Personalizados",
    category: "Core",
    description: "Custom fields e managed fields com sugestões IA",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Campos Personalizados", route: "/dashboard/settings/fields" }],
    hooks: ["useCustomFields", "useManagedFields"],
    edgeFunctions: ["ai-field-suggestions"],
    tables: ["custom_fields", "managed_fields", "ai_field_suggestions"],
    features: [
      { name: "Custom fields", description: "Criar campos personalizados por entidade", status: "active", aiPowered: false },
      { name: "Managed fields", description: "Campos geridos pelo sistema com regras", status: "active", aiPowered: false },
      { name: "Sugestões IA", description: "Sugestões automáticas de valores para campos", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "core-settings",
    name: "Configurações",
    category: "Core",
    description: "Gestão de equipa, permissões, facturação e integrações",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Equipa", route: "/dashboard/settings/team" },
      { name: "Permissões", route: "/dashboard/settings/permissions" },
      { name: "Facturação", route: "/dashboard/settings/billing" },
      { name: "Integrações", route: "/dashboard/settings/integrations" },
    ],
    hooks: ["useWorkspaceMembers", "useWorkspaceSettings"],
    edgeFunctions: [],
    tables: ["workspace_members", "workspace_settings", "workspace_invites"],
    features: [
      { name: "Gestão de equipa", description: "Convidar e gerir membros do workspace", status: "active", aiPowered: false },
      { name: "Permissões", description: "Controlar acessos por role", status: "active", aiPowered: false },
      { name: "Facturação", description: "Gerir plano e pagamentos", status: "active", aiPowered: false },
      { name: "Integrações", description: "Conectar serviços externos", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },

  // ══════════ CRM ══════════
  {
    id: "crm-leads",
    name: "Leads",
    category: "CRM",
    description: "Gestão completa de potenciais clientes com scoring e IA",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Lista de Leads", route: "/dashboard/leads" },
      { name: "Detalhe do Lead", route: "/dashboard/leads/:id" },
    ],
    hooks: ["useLeads", "useSmartLeads", "useLeadEnrichment", "useAutoTags"],
    edgeFunctions: ["ai-analyze-lead", "create-demo-lead", "create-public-lead", "compute-lead-behavior-signals"],
    tables: ["leads", "lead_activities", "lead_tags", "lead_scoring_rules"],
    features: [
      { name: "CRUD Leads", description: "Criar, editar e apagar leads", status: "active", aiPowered: false },
      { name: "Lead Scoring IA", description: "Pontuação automática com análise de perfil", status: "active", aiPowered: true },
      { name: "Auto Tags", description: "Etiquetas automáticas baseadas em comportamento", status: "active", aiPowered: true },
      { name: "Detecção de Duplicados", description: "Identificar e fundir leads duplicados", status: "active", aiPowered: false },
      { name: "Timeline de Actividades", description: "Histórico completo de interacções", status: "active", aiPowered: false },
      { name: "Bulk Outreach", description: "Envio em massa de mensagens personalizadas", status: "active", aiPowered: true },
      { name: "Importar CSV", description: "Importação em massa via ficheiro", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "crm-lead-enricher",
    name: "Lead Enricher",
    category: "CRM",
    description: "Enriquecimento automático de leads via IA, Google e Instagram",
    minPlan: "pro",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Lead Enricher", route: "/dashboard/leads/enricher" }],
    hooks: ["useLeadEnrichment", "useInstagramEnrich"],
    edgeFunctions: ["enrich-instagram-profile", "google-places-enrich"],
    tables: ["leads"],
    features: [
      { name: "Enriquecimento IA", description: "Preencher dados automaticamente com IA", status: "active", aiPowered: true },
      { name: "Pesquisa Google", description: "Encontrar informações via Google Places", status: "active", aiPowered: false },
      { name: "Instagram Profile", description: "Extrair dados de perfis Instagram", status: "active", aiPowered: false },
    ],
    dependencies: ["crm-leads"],
  },
  {
    id: "crm-contacts",
    name: "Contactos",
    category: "CRM",
    description: "Gestão de contactos com merge de duplicados e insights",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Lista de Contactos", route: "/dashboard/contacts" },
      { name: "Detalhe do Contacto", route: "/dashboard/contacts/:id" },
    ],
    hooks: ["useContacts", "useContactInsights"],
    edgeFunctions: ["contact-enrich", "contact-insights"],
    tables: ["contacts", "contact_emails", "contact_phones"],
    features: [
      { name: "CRUD Contactos", description: "Criar, editar e apagar contactos", status: "active", aiPowered: false },
      { name: "Merge duplicados", description: "Fundir contactos duplicados automaticamente", status: "active", aiPowered: false },
      { name: "Histórico email", description: "Ver histórico de emails trocados", status: "active", aiPowered: false },
      { name: "Enriquecimento", description: "Preencher dados com fontes externas", status: "active", aiPowered: true },
      { name: "Insights IA", description: "Análise inteligente do contacto", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "crm-companies",
    name: "Empresas",
    category: "CRM",
    description: "Gestão de empresas com NIF lookup e enriquecimento",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Lista de Empresas", route: "/dashboard/companies" },
      { name: "Detalhe da Empresa", route: "/dashboard/companies/:id" },
    ],
    hooks: ["useCompanies", "useCompanyEnrich"],
    edgeFunctions: ["company-enrich", "company-insights", "enrich-company-data", "lookup-company-nif"],
    tables: ["companies", "company_contacts"],
    features: [
      { name: "CRUD Empresas", description: "Criar, editar e apagar empresas", status: "active", aiPowered: false },
      { name: "NIF Lookup", description: "Pesquisar empresa por NIF português", status: "active", aiPowered: false },
      { name: "Enriquecimento", description: "Preencher dados automaticamente", status: "active", aiPowered: true },
      { name: "Detecção duplicados", description: "Identificar empresas duplicadas", status: "active", aiPowered: false },
      { name: "Insights IA", description: "Análise inteligente da empresa", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "crm-opportunities",
    name: "Oportunidades",
    category: "CRM",
    description: "Pipeline Kanban com deal scoring e coach IA",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Pipeline", route: "/dashboard/opportunities" },
      { name: "Detalhe", route: "/dashboard/opportunities/:id" },
      { name: "Configurar Pipeline", route: "/dashboard/opportunities/settings" },
    ],
    hooks: ["useOpportunities", "usePipelineStages", "useDealScore"],
    edgeFunctions: ["compute-deal-score", "ai-opportunity-coach"],
    tables: ["opportunities", "pipeline_stages", "opportunity_activities"],
    features: [
      { name: "Pipeline Kanban", description: "Visualizar oportunidades em colunas", status: "active", aiPowered: false },
      { name: "Deal Scoring", description: "Pontuação automática de oportunidades", status: "active", aiPowered: true },
      { name: "Coach IA", description: "Sugestões para fechar negócios", status: "active", aiPowered: true },
      { name: "Multi-pipeline", description: "Múltiplos pipelines por workspace", status: "active", aiPowered: false },
    ],
    dependencies: ["crm-leads", "crm-contacts"],
  },
  {
    id: "crm-fastmatch",
    name: "FastMatch",
    category: "CRM",
    description: "Conexões estratégicas entre contactos e oportunidades",
    minPlan: "pro",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "FastMatch", route: "/dashboard/fastmatch" }],
    hooks: ["useFastMatch"],
    edgeFunctions: [],
    tables: ["fast_match_profiles", "fast_match_connections"],
    features: [
      { name: "Perfis", description: "Criar perfis de interesses e competências", status: "active", aiPowered: false },
      { name: "Conexões", description: "Encontrar matches estratégicos", status: "active", aiPowered: false },
    ],
    dependencies: ["crm-contacts"],
  },

  // ══════════ COMUNICAÇÃO ══════════
  {
    id: "comm-inbox",
    name: "Inbox",
    category: "Comunicação",
    description: "Inbox unificado com classificação e respostas IA",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Inbox", route: "/dashboard/inbox" }],
    hooks: ["useConversations", "useMessages", "useInboxActions"],
    edgeFunctions: ["ai-inbox-reply", "ai-inbox-actions", "classify-conversation", "conversation-intelligence"],
    tables: ["conversations", "messages", "conversation_tags"],
    features: [
      { name: "Inbox unificado", description: "Todas as mensagens num só lugar", status: "active", aiPowered: false },
      { name: "Classificação IA", description: "Classificar conversas automaticamente", status: "active", aiPowered: true },
      { name: "Respostas IA", description: "Gerar respostas inteligentes", status: "active", aiPowered: true },
      { name: "Acções IA", description: "Executar acções sugeridas pela IA", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "comm-email",
    name: "Email",
    category: "Comunicação",
    description: "Conexão IMAP/SMTP, envio de emails e webhooks",
    minPlan: "basic",
    status: "active",
    moduleSlug: null,
    pages: [],
    hooks: ["useEmailConnection", "useEmailSend"],
    edgeFunctions: ["email-send", "email-fetch", "email-connect", "email-disconnect", "email-webhook"],
    tables: ["email_accounts", "email_messages"],
    features: [
      { name: "Conexão IMAP", description: "Conectar conta de email via IMAP", status: "active", aiPowered: false },
      { name: "Envio emails", description: "Enviar emails directamente do CRM", status: "active", aiPowered: false },
      { name: "Webhooks", description: "Receber notificações de emails", status: "active", aiPowered: false },
    ],
    dependencies: ["comm-inbox"],
  },
  {
    id: "comm-templates",
    name: "Templates",
    category: "Comunicação",
    description: "Criar e gerar templates de mensagens com IA",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Templates", route: "/dashboard/templates" }],
    hooks: ["useTemplates", "useTemplateCopilot"],
    edgeFunctions: ["generate-template", "ai-template-copilot", "template-compose-message"],
    tables: ["email_templates", "template_variables"],
    features: [
      { name: "Criar templates", description: "Criar templates de mensagens reutilizáveis", status: "active", aiPowered: false },
      { name: "Gerar com IA", description: "Gerar templates automaticamente", status: "active", aiPowered: true },
      { name: "Variações", description: "Criar variações A/B de templates", status: "active", aiPowered: true },
      { name: "Estatísticas", description: "Ver performance de cada template", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },

  // ══════════ VENDAS ══════════
  {
    id: "sales-proposals",
    name: "Propostas",
    category: "Vendas",
    description: "Criar propostas comerciais com checkout e narração IA",
    minPlan: "basic",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Lista de Propostas", route: "/dashboard/proposals" },
      { name: "Editor", route: "/dashboard/proposals/:id" },
      { name: "Checkout Público", route: "/proposal/:token" },
    ],
    hooks: ["useProposals", "useProposalItems", "useProposalCheckout"],
    edgeFunctions: ["generate-proposal-copy", "ai-proposal-assistant", "proposal-checkout", "proposal-webhook", "elevenlabs-proposal-token"],
    tables: ["proposals", "proposal_items", "proposal_signatures"],
    features: [
      { name: "Criar propostas", description: "Construir propostas comerciais profissionais", status: "active", aiPowered: false },
      { name: "Copy IA", description: "Gerar texto comercial com IA", status: "active", aiPowered: true },
      { name: "Checkout", description: "Página de aceitação e pagamento", status: "active", aiPowered: false },
      { name: "Narração IA", description: "Narrar proposta com voz IA (ElevenLabs)", status: "active", aiPowered: true },
      { name: "PDF Export", description: "Exportar proposta em PDF", status: "active", aiPowered: false },
    ],
    dependencies: ["crm-contacts"],
  },
  {
    id: "sales-invoices",
    name: "Facturas",
    category: "Vendas",
    description: "Facturação com items e exportação SAF-T",
    minPlan: "basic",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Lista de Facturas", route: "/dashboard/invoices" },
      { name: "Editor", route: "/dashboard/invoices/:id" },
    ],
    hooks: ["useInvoices", "useInvoiceItems"],
    edgeFunctions: ["saft-export"],
    tables: ["invoices", "invoice_items"],
    features: [
      { name: "Criar facturas", description: "Emitir facturas com items", status: "active", aiPowered: false },
      { name: "SAF-T Export", description: "Exportar dados no formato SAF-T PT", status: "active", aiPowered: false },
      { name: "Numeração automática", description: "Numeração sequencial automática", status: "active", aiPowered: false },
    ],
    dependencies: ["crm-contacts"],
  },
  {
    id: "sales-products",
    name: "Produtos",
    category: "Vendas",
    description: "Catálogo de produtos com variantes, imagens e IA",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Catálogo", route: "/dashboard/products" },
      { name: "Detalhe", route: "/dashboard/products/:id" },
    ],
    hooks: ["useProducts", "useProductCategories", "useProductAIImprove"],
    edgeFunctions: ["ai-product-assistant", "product-embedding", "product-semantic-search", "product-publish"],
    tables: ["products", "product_categories", "product_images", "product_variants"],
    features: [
      { name: "Catálogo", description: "Gerir catálogo completo de produtos", status: "active", aiPowered: false },
      { name: "Variantes", description: "Criar variações (tamanho, cor, etc.)", status: "active", aiPowered: false },
      { name: "Imagens", description: "Upload e gestão de imagens", status: "active", aiPowered: false },
      { name: "Ficha pública", description: "Página pública do produto", status: "active", aiPowered: false },
      { name: "Descrição IA", description: "Gerar descrições com IA", status: "active", aiPowered: true },
      { name: "Pesquisa semântica", description: "Pesquisar produtos por significado", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "sales-order-notes",
    name: "Notas de Encomenda",
    category: "Vendas",
    description: "Criar, aprovar e converter notas de encomenda em facturas",
    minPlan: "basic",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Lista", route: "/dashboard/order-notes" },
      { name: "Detalhe", route: "/dashboard/order-notes/:id" },
    ],
    hooks: ["useOrderNotes", "useOrderNoteItems"],
    edgeFunctions: ["order-note-submit", "order-note-notify"],
    tables: ["order_notes", "order_note_items"],
    features: [
      { name: "Criar notas", description: "Emitir notas de encomenda", status: "active", aiPowered: false },
      { name: "Aprovar", description: "Fluxo de aprovação de encomendas", status: "active", aiPowered: false },
      { name: "Converter", description: "Converter nota em factura", status: "active", aiPowered: false },
    ],
    dependencies: ["sales-products", "crm-contacts"],
  },
  {
    id: "sales-bundles",
    name: "Pacotes & Bundles",
    category: "Vendas",
    description: "Bundles de produtos com checkout integrado",
    minPlan: "pro",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Bundles", route: "/dashboard/bundles" }],
    hooks: ["useBundles"],
    edgeFunctions: ["bundle-checkout"],
    tables: ["bundles", "bundle_items"],
    features: [
      { name: "Criar bundles", description: "Agrupar produtos em pacotes", status: "active", aiPowered: false },
      { name: "Checkout", description: "Página de checkout de bundles", status: "active", aiPowered: false },
    ],
    dependencies: ["sales-products"],
  },

  // ══════════ MARKETING ══════════
  {
    id: "mkt-email",
    name: "Email Marketing",
    category: "Marketing",
    description: "Campanhas de email com segmentos e analytics",
    minPlan: "basic",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Campanhas", route: "/dashboard/email-campaigns" }],
    hooks: ["useEmailCampaigns", "useCampaignAnalytics"],
    edgeFunctions: ["marketing-send-campaign", "marketing-campaign-insights"],
    tables: ["email_campaigns", "campaign_recipients", "campaign_analytics"],
    features: [
      { name: "Criar campanhas", description: "Compor campanhas de email marketing", status: "active", aiPowered: false },
      { name: "Segmentos", description: "Segmentar destinatários por critérios", status: "active", aiPowered: false },
      { name: "Analytics", description: "Métricas de abertura, cliques e conversões", status: "active", aiPowered: false },
      { name: "Insights IA", description: "Análise inteligente de performance", status: "active", aiPowered: true },
    ],
    dependencies: ["crm-contacts"],
  },
  {
    id: "mkt-funnels",
    name: "Funis",
    category: "Marketing",
    description: "Funis multi-step com testes A/B e estratégia IA",
    minPlan: "pro",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Funis", route: "/dashboard/funnels" }],
    hooks: ["useFunnels", "useFunnelSteps"],
    edgeFunctions: ["funnel-ai-insights", "funnel-ai-strategist"],
    tables: ["funnels", "funnel_steps", "funnel_conversions"],
    features: [
      { name: "Multi-step", description: "Criar funis com múltiplos passos", status: "active", aiPowered: false },
      { name: "Testes A/B", description: "Testar variações de cada passo", status: "active", aiPowered: false },
      { name: "Insights IA", description: "Análise e optimização com IA", status: "active", aiPowered: true },
      { name: "Estrategista IA", description: "Sugestões de estratégia de funil", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "mkt-landing",
    name: "Landing Pages",
    category: "Marketing",
    description: "Páginas de aterragem com copy gerado por IA",
    minPlan: "basic",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Landing Pages", route: "/dashboard/landing-pages" },
      { name: "Página Pública", route: "/lp/:slug" },
    ],
    hooks: ["useLandingPages"],
    edgeFunctions: ["landing-page-copy"],
    tables: ["landing_pages", "landing_page_sections"],
    features: [
      { name: "Criar páginas", description: "Construir landing pages", status: "active", aiPowered: false },
      { name: "Copy IA", description: "Gerar textos de conversão com IA", status: "active", aiPowered: true },
      { name: "Publicar", description: "Publicar com URL personalizado", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "mkt-bio",
    name: "Bio OS",
    category: "Marketing",
    description: "Páginas bio com blocos, links inteligentes e IA",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Bio Pages", route: "/dashboard/bio" }],
    hooks: ["useBioPages", "useBioBlocks"],
    edgeFunctions: ["bio-ai-builder", "bio-generate-image", "bio-seo-copy", "bio-smart-link", "bio-whatsapp-copy"],
    tables: ["bio_pages", "bio_blocks", "bio_analytics"],
    features: [
      { name: "Páginas bio", description: "Criar link-in-bio personalizável", status: "active", aiPowered: false },
      { name: "Blocos", description: "Adicionar blocos de conteúdo variado", status: "active", aiPowered: false },
      { name: "Builder IA", description: "Gerar página bio completa com IA", status: "active", aiPowered: true },
      { name: "SEO Copy", description: "Optimizar textos para SEO", status: "active", aiPowered: true },
      { name: "Smart Links", description: "Links inteligentes com tracking", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "mkt-prospecting",
    name: "Prospecção",
    category: "Marketing",
    description: "Pesquisa de prospects via Google Maps e web scraping",
    minPlan: "pro",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Prospecção", route: "/dashboard/prospecting" },
      { name: "Prospecção Pro", route: "/dashboard/prospecting/pro" },
    ],
    hooks: ["useProspecting", "useProspectingSearch"],
    edgeFunctions: ["google-local-search", "professional-prospecting-search", "professional-prospecting-analyze", "firecrawl-search"],
    tables: ["prospecting_results", "prospecting_campaigns"],
    features: [
      { name: "Google Maps", description: "Pesquisar negócios por localização", status: "active", aiPowered: false },
      { name: "Web Search", description: "Pesquisa profissional na web", status: "active", aiPowered: false },
      { name: "Análise IA", description: "Analisar perfil de prospects", status: "active", aiPowered: true },
    ],
    dependencies: ["crm-leads"],
  },

  // ══════════ LOJA ONLINE ══════════
  {
    id: "store-ecommerce",
    name: "E-Commerce",
    category: "Loja Online",
    description: "Loja online completa com produtos, categorias e encomendas",
    minPlan: "pro",
    status: "active",
    moduleSlug: "loja-online",
    pages: [
      { name: "Produtos", route: "/dashboard/store/products" },
      { name: "Categorias", route: "/dashboard/store/categories" },
      { name: "Encomendas", route: "/dashboard/store/orders" },
      { name: "Cupões", route: "/dashboard/store/coupons" },
      { name: "Analytics", route: "/dashboard/store/analytics" },
      { name: "Configurações", route: "/dashboard/store/settings" },
      { name: "Loja Pública", route: "/store/:slug" },
    ],
    hooks: ["useStoreProducts", "useStoreOrders", "useStoreCoupons", "useStoreAnalytics"],
    edgeFunctions: ["create-store-checkout", "store-webhook", "store-ai-advisor", "store-capture-lead", "detect-abandoned-carts", "store-visual-search"],
    tables: ["store_products", "store_categories", "store_orders", "store_order_items", "store_coupons", "store_settings"],
    features: [
      { name: "Catálogo", description: "Gerir produtos da loja", status: "active", aiPowered: false },
      { name: "Categorias", description: "Organizar produtos em categorias", status: "active", aiPowered: false },
      { name: "Checkout", description: "Processo de checkout seguro", status: "active", aiPowered: false },
      { name: "Cupões", description: "Criar códigos de desconto", status: "active", aiPowered: false },
      { name: "Carrinhos abandonados", description: "Detectar e recuperar carrinhos", status: "active", aiPowered: true },
      { name: "Advisor IA", description: "Assistente de vendas inteligente", status: "active", aiPowered: true },
      { name: "Pesquisa visual", description: "Pesquisar produtos por imagem", status: "active", aiPowered: true },
    ],
    dependencies: ["sales-products"],
  },
  {
    id: "store-c2c",
    name: "Marketplace C2C",
    category: "Loja Online",
    description: "Marketplace entre utilizadores com boost e mensagens",
    minPlan: "pro",
    status: "active",
    moduleSlug: "marketplace-c2c",
    pages: [
      { name: "Anúncios", route: "/dashboard/c2c/listings" },
      { name: "Vendedores", route: "/dashboard/c2c/sellers" },
      { name: "Mensagens", route: "/dashboard/c2c/messages" },
      { name: "Sponsors", route: "/dashboard/c2c/sponsors" },
      { name: "Configurações", route: "/dashboard/c2c/settings" },
      { name: "Marketplace Público", route: "/marketplace/:slug" },
    ],
    hooks: ["useC2CListings", "useC2CSellers", "useC2CMessages"],
    edgeFunctions: ["create-c2c-checkout", "create-c2c-boost-checkout", "c2c-webhook", "ai-c2c-listing-assistant"],
    tables: ["c2c_listings", "c2c_offers", "c2c_messages", "c2c_sellers", "c2c_sponsors"],
    features: [
      { name: "Anúncios", description: "Publicar e gerir anúncios", status: "active", aiPowered: false },
      { name: "Boost", description: "Promover anúncios com pagamento", status: "active", aiPowered: false },
      { name: "Mensagens", description: "Chat entre compradores e vendedores", status: "active", aiPowered: false },
      { name: "Assistente IA", description: "Ajuda na criação de anúncios", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },

  // ══════════ PORTAL B2B ══════════
  {
    id: "b2b-core",
    name: "Portal B2B (Core)",
    category: "Portal B2B",
    description: "Gestão de clientes empresariais com autenticação dedicada, convites, activação de conta e sistema de roles (client_admin, client_financial, client_operational, client_viewer)",
    minPlan: "pro",
    status: "active",
    moduleSlug: "portal-b2b",
    pages: [
      { name: "Clientes B2B", route: "/dashboard/b2b/clients" },
      { name: "Client Users", route: "/dashboard/b2b/users" },
      { name: "Portal Público (Login)", route: "/client-portal/login" },
      { name: "Activação Convite", route: "/client-portal/invite/:token" },
    ],
    hooks: ["useClientAuth", "useClientPermissions", "useB2BClients"],
    edgeFunctions: ["create-client-auth-user", "send-client-invitation", "activate-client-invite"],
    tables: ["client_users", "client_user_roles", "client_companies", "b2b_clients"],
    features: [
      { name: "Gestão de clientes", description: "Criar e gerir empresas clientes com condições comerciais", status: "active", aiPowered: false },
      { name: "Convites por email", description: "Enviar convites personalizáveis com token seguro", status: "active", aiPowered: false },
      { name: "Activação de conta", description: "Fluxo de activação em 2 fases (pending → active)", status: "active", aiPowered: false },
      { name: "Sistema de roles", description: "4 roles com permissões granulares por funcionalidade", status: "active", aiPowered: false },
      { name: "Autenticação dedicada", description: "Login isolado do CRM principal com sessão própria", status: "active", aiPowered: false },
    ],
    dependencies: ["crm-companies"],
  },
  {
    id: "b2b-catalog-orders",
    name: "Catálogo & Encomendas",
    category: "Portal B2B",
    description: "Catálogo de produtos com pesquisa, carrinho de compras, checkout com cálculo automático de IVA, favoritos e re-encomenda em 1 clique",
    minPlan: "pro",
    status: "active",
    moduleSlug: "portal-b2b",
    pages: [
      { name: "Catálogo", route: "/client-portal/catalog" },
      { name: "Carrinho", route: "/client-portal/cart" },
      { name: "Checkout", route: "/client-portal/checkout" },
      { name: "Encomendas", route: "/client-portal/orders" },
      { name: "Favoritos", route: "/client-portal/favorites" },
    ],
    hooks: ["useClientOrders", "useClientProducts", "useClientFavorites", "useCart"],
    edgeFunctions: [],
    tables: ["client_orders", "client_order_items", "client_favorites", "products"],
    features: [
      { name: "Catálogo de produtos", description: "Navegação por categorias com preços B2B", status: "active", aiPowered: false },
      { name: "Carrinho de compras", description: "Gestão de carrinho com quantidades e subtotais", status: "active", aiPowered: false },
      { name: "Checkout com IVA", description: "Cálculo automático de IVA e finalização de encomenda", status: "active", aiPowered: false },
      { name: "Favoritos", description: "Guardar produtos favoritos para acesso rápido", status: "active", aiPowered: false },
      { name: "Re-encomenda 1 clique", description: "Repetir encomendas anteriores com um clique", status: "active", aiPowered: false },
      { name: "Pagamento em prestações", description: "Opção de parcelamento para encomendas grandes", status: "active", aiPowered: false },
    ],
    dependencies: ["b2b-core"],
  },
  {
    id: "b2b-approvals",
    name: "Aprovações & Workflow",
    category: "Portal B2B",
    description: "Fluxo de aprovação de encomendas com limites de gastos por role, centro de aprovação para administradores e categorias de produtos permitidas",
    minPlan: "pro",
    status: "active",
    moduleSlug: "portal-b2b",
    pages: [
      { name: "Centro de Aprovação", route: "/client-portal/approvals" },
      { name: "Aprovações (Admin CRM)", route: "/dashboard/b2b/approvals" },
    ],
    hooks: ["useClientApprovals"],
    edgeFunctions: [],
    tables: ["client_orders", "client_user_roles"],
    features: [
      { name: "Fluxo de aprovação", description: "Encomendas aguardam aprovação quando excedem limites", status: "active", aiPowered: false },
      { name: "Limites de gastos", description: "Limites configuráveis por role e utilizador", status: "active", aiPowered: false },
      { name: "Centro de aprovação", description: "Dashboard dedicado para aprovar/rejeitar encomendas", status: "active", aiPowered: false },
      { name: "Categorias permitidas", description: "Restrição de compras por categoria de produto", status: "active", aiPowered: false },
    ],
    dependencies: ["b2b-core", "b2b-catalog-orders"],
  },
  {
    id: "b2b-financial",
    name: "Financeiro",
    category: "Portal B2B",
    description: "Gestão financeira com histórico de faturas, contratos com SLAs, e visibilidade financeira controlada por roles",
    minPlan: "pro",
    status: "active",
    moduleSlug: "portal-b2b",
    pages: [
      { name: "Faturas", route: "/client-portal/invoices" },
      { name: "Contratos", route: "/client-portal/contracts" },
      { name: "Histórico Financeiro", route: "/client-portal/financial" },
    ],
    hooks: ["useClientInvoices", "useClientContracts"],
    edgeFunctions: [],
    tables: ["client_invoices", "client_contracts"],
    features: [
      { name: "Faturas", description: "Consulta e download de faturas com filtros", status: "active", aiPowered: false },
      { name: "Contratos", description: "Visualização de contratos activos com detalhes", status: "active", aiPowered: false },
      { name: "SLAs", description: "Acompanhamento de níveis de serviço acordados", status: "active", aiPowered: false },
      { name: "Histórico financeiro", description: "Timeline completa de transacções e pagamentos", status: "active", aiPowered: false },
    ],
    dependencies: ["b2b-core"],
  },
  {
    id: "b2b-support",
    name: "Suporte & Tickets",
    category: "Portal B2B",
    description: "Sistema de tickets de suporte com tipos (support, commercial, technical), prioridades, SLA deadlines e mensagens bidirecionais",
    minPlan: "pro",
    status: "active",
    moduleSlug: "portal-b2b",
    pages: [
      { name: "Tickets", route: "/client-portal/tickets" },
      { name: "Detalhe Ticket", route: "/client-portal/tickets/:id" },
    ],
    hooks: ["useClientTickets", "useTicketMessages"],
    edgeFunctions: [],
    tables: ["client_tickets", "client_ticket_messages"],
    features: [
      { name: "Criar tickets", description: "Abrir tickets de suporte, comerciais ou técnicos", status: "active", aiPowered: false },
      { name: "Mensagens", description: "Chat bidirecional entre cliente e agente", status: "active", aiPowered: false },
      { name: "Estados e prioridades", description: "Workflow de estados (open → resolved) com prioridades", status: "active", aiPowered: false },
      { name: "SLA deadlines", description: "Prazos de resposta automáticos por prioridade", status: "active", aiPowered: false },
    ],
    dependencies: ["b2b-core"],
  },
  {
    id: "b2b-intelligence",
    name: "Intelligence Hub",
    category: "Portal B2B",
    description: "Hub de inteligência B2B com Copilot IA para apoio à decisão, pesquisa semântica de produtos, diagnóstico assistido e protocolos de recomendação",
    minPlan: "pro",
    status: "active",
    moduleSlug: "portal-b2b",
    pages: [
      { name: "Copilot B2B", route: "/client-portal/assistant" },
      { name: "Protocolos", route: "/client-portal/protocols" },
    ],
    hooks: ["useDiagnosticAssistant", "useProductSemanticSearch", "useProtocols"],
    edgeFunctions: ["ai-diagnostic-assistant", "product-semantic-search"],
    tables: ["product_protocols", "protocol_products", "product_embeddings"],
    features: [
      { name: "Copilot B2B", description: "Assistente IA com contexto comercial da empresa", status: "active", aiPowered: true },
      { name: "Pesquisa semântica", description: "Busca de produtos por linguagem natural com embeddings", status: "active", aiPowered: true },
      { name: "Diagnóstico IA", description: "Análise de necessidades com recomendação de produtos", status: "active", aiPowered: true },
      { name: "Protocolos", description: "Kits de produtos recomendados por categoria/procedimento", status: "active", aiPowered: false },
      { name: "Recomendações", description: "Sugestões baseadas no histórico de compras", status: "active", aiPowered: true },
    ],
    dependencies: ["b2b-core", "b2b-catalog-orders"],
  },

  // ══════════ COMUNIDADE ══════════
  {
    id: "community-fastclub",
    name: "FastClub",
    category: "Comunidade",
    description: "Portal de comunidade com candidaturas e capital circle",
    minPlan: "pro",
    status: "active",
    moduleSlug: "fastclub",
    pages: [
      { name: "FastClub", route: "/dashboard/fastclub" },
      { name: "Portal Público", route: "/club/:slug" },
    ],
    hooks: ["useFastClub", "useFastClubApplications"],
    edgeFunctions: ["fastclub-application-processor", "send-community-invite", "generate-community-banner"],
    tables: ["fastclub_members", "fastclub_applications", "capital_circle"],
    features: [
      { name: "Portal", description: "Portal de comunidade exclusivo", status: "active", aiPowered: false },
      { name: "Candidaturas", description: "Processar candidaturas de membros", status: "active", aiPowered: true },
      { name: "Capital Circle", description: "Rede de investidores e networking", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "community-forum",
    name: "Comunidade",
    category: "Comunidade",
    description: "Fórum com canais, eventos e moderação IA",
    minPlan: "basic",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Canais", route: "/dashboard/community/channels" },
      { name: "Fórum", route: "/dashboard/community/forum" },
      { name: "Eventos", route: "/dashboard/community/events" },
    ],
    hooks: ["useCommunityChannels", "useCommunityPosts", "useCommunityEvents"],
    edgeFunctions: ["community-ai-category", "community-ai-suggest-title"],
    tables: ["community_channels", "community_posts", "community_events", "community_members"],
    features: [
      { name: "Canais", description: "Criar canais temáticos", status: "active", aiPowered: false },
      { name: "Fórum", description: "Discussões em formato fórum", status: "active", aiPowered: false },
      { name: "Eventos", description: "Criar e gerir eventos comunitários", status: "active", aiPowered: false },
      { name: "Categorização IA", description: "Categorizar posts automaticamente", status: "active", aiPowered: true },
      { name: "Sugestão títulos", description: "Sugerir títulos com IA", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },

  // ══════════ IA ══════════
  {
    id: "ai-copilot",
    name: "AI Copilot",
    category: "IA",
    description: "Assistência contextual por IA em qualquer página",
    minPlan: "basic",
    status: "active",
    moduleSlug: "ai-copilot",
    pages: [],
    hooks: ["useAICopilot"],
    edgeFunctions: ["ai-copilot"],
    tables: [],
    features: [
      { name: "Assistência contextual", description: "Chat IA integrado em qualquer página", status: "active", aiPowered: true },
      { name: "Acções rápidas", description: "Executar acções via linguagem natural", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "ai-employees",
    name: "AI Employees",
    category: "IA",
    description: "Operadores digitais autónomos para tarefas repetitivas",
    minPlan: "pro",
    status: "active",
    moduleSlug: "ai-assistants",
    pages: [
      { name: "AI Employees", route: "/dashboard/ai-employees" },
      { name: "Configurar", route: "/dashboard/ai-employees/:id" },
      { name: "Execuções", route: "/dashboard/ai-employees/executions" },
    ],
    hooks: ["useAIEmployees", "useAIEmployeeExecutions"],
    edgeFunctions: ["ai-employee-executor"],
    tables: ["ai_employees", "ai_employee_executions"],
    features: [
      { name: "Criar operadores", description: "Definir agentes digitais autónomos", status: "active", aiPowered: true },
      { name: "Execuções", description: "Monitorizar tarefas executadas", status: "active", aiPowered: false },
      { name: "Agendamento", description: "Agendar execuções periódicas", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "ai-assistants",
    name: "AI Assistentes",
    category: "IA",
    description: "Personas, vibe profiles e fluxos conversacionais",
    minPlan: "basic",
    status: "active",
    moduleSlug: "ai-assistants",
    pages: [{ name: "Assistentes", route: "/dashboard/ai-assistants" }],
    hooks: ["useAIPersonas", "useVibeProfiles"],
    edgeFunctions: [],
    tables: ["ai_personas", "vibe_profiles", "ai_agents"],
    features: [
      { name: "Personas", description: "Criar personalidades de IA", status: "active", aiPowered: false },
      { name: "Vibe Profiles", description: "Definir tom e estilo de comunicação", status: "active", aiPowered: false },
      { name: "Fluxos", description: "Configurar fluxos conversacionais", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "ai-conversational",
    name: "Motor Conversacional",
    category: "IA",
    description: "Regras, objectivos e classificação de conversas",
    minPlan: "pro",
    status: "active",
    moduleSlug: "ai-conversational-engine",
    pages: [{ name: "Motor", route: "/dashboard/ai-engine" }],
    hooks: ["useConversationalEngine", "useConversationClassification"],
    edgeFunctions: ["classify-conversation", "conversation-intelligence", "conversation-summary"],
    tables: ["conversation_rules", "conversation_goals", "conversation_classifications"],
    features: [
      { name: "Regras", description: "Definir regras de resposta automática", status: "active", aiPowered: true },
      { name: "Objectivos", description: "Configurar objectivos de conversa", status: "active", aiPowered: true },
      { name: "Classificação", description: "Classificar conversas automaticamente", status: "active", aiPowered: true },
      { name: "Resumos", description: "Gerar resumos de conversas", status: "active", aiPowered: true },
    ],
    dependencies: ["comm-inbox", "ai-assistants"],
  },
  {
    id: "ai-knowledge",
    name: "Knowledge Base",
    category: "IA",
    description: "Base de conhecimento RAG com pesquisa semântica",
    minPlan: "basic",
    status: "active",
    moduleSlug: "ai-knowledge-base",
    pages: [{ name: "Knowledge Base", route: "/dashboard/knowledge" }],
    hooks: ["useKnowledgeBases", "useKnowledgeDocuments"],
    edgeFunctions: ["knowledge-query", "knowledge-embedding", "knowledge-semantic-search", "knowledge-document-process"],
    tables: ["knowledge_bases", "knowledge_documents", "knowledge_chunks"],
    features: [
      { name: "Upload documentos", description: "Carregar documentos para a base", status: "active", aiPowered: false },
      { name: "RAG", description: "Retrieval-Augmented Generation", status: "active", aiPowered: true },
      { name: "Pesquisa semântica", description: "Pesquisar por significado", status: "active", aiPowered: true },
      { name: "Embeddings", description: "Gerar embeddings vectoriais", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "ai-suggestions",
    name: "AI Sugestões",
    category: "IA",
    description: "Sugestões automáticas de tags, campos e automações",
    minPlan: "basic",
    status: "active",
    moduleSlug: "ai-suggestions",
    pages: [{ name: "Sugestões", route: "/dashboard/ai-suggestions" }],
    hooks: ["useAISuggestions", "useAutoTags"],
    edgeFunctions: ["ai-field-suggestions", "ai-auto-tags", "ai-automation-suggestions"],
    tables: ["ai_field_suggestions"],
    features: [
      { name: "Auto Tags", description: "Sugerir etiquetas automaticamente", status: "active", aiPowered: true },
      { name: "Campos", description: "Sugerir valores para campos", status: "active", aiPowered: true },
      { name: "Automações", description: "Sugerir regras de automação", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "ai-agents",
    name: "AI Agents",
    category: "IA",
    description: "Pipeline de agentes autónomos com orchestração",
    minPlan: "agency",
    status: "active",
    moduleSlug: null,
    pages: [],
    hooks: ["useAIAgentJobs", "useAIAgentExecutions"],
    edgeFunctions: ["ai-agent-orchestrator", "ai-agent-processor", "ai-agent-scheduler", "ai-agent-lifecycle", "ai-agent-client", "ai-agent-opportunity"],
    tables: ["ai_agent_jobs", "ai_agent_executions", "ai_agent_registry", "ai_agent_memory", "ai_agent_locks", "ai_agent_schedules"],
    features: [
      { name: "Orchestração", description: "Orquestrar múltiplos agentes", status: "active", aiPowered: true },
      { name: "Jobs", description: "Fila de trabalhos para agentes", status: "active", aiPowered: true },
      { name: "Memória", description: "Memória persistente entre execuções", status: "active", aiPowered: true },
      { name: "Agendamento", description: "Agendar execuções periódicas", status: "active", aiPowered: true },
      { name: "Cache", description: "Cache de respostas para performance", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "ai-docint",
    name: "Document Intelligence",
    category: "IA",
    description: "OCR, classificação e extracção de documentos",
    minPlan: "pro",
    status: "active",
    moduleSlug: "ai-ocr-documents",
    pages: [],
    hooks: ["useDocumentProcessing"],
    edgeFunctions: ["knowledge-document-process", "knowledge-document-trigger"],
    tables: ["document_processing_jobs"],
    features: [
      { name: "OCR", description: "Extrair texto de imagens e PDFs", status: "active", aiPowered: true },
      { name: "Classificação", description: "Classificar tipo de documento", status: "active", aiPowered: true },
      { name: "Extracção", description: "Extrair dados estruturados", status: "active", aiPowered: true },
    ],
    dependencies: ["ai-knowledge"],
  },

  // ══════════ ESTRATÉGIA ══════════
  {
    id: "strategy-command-center",
    name: "Command Center",
    category: "Estratégia",
    description: "Cockpit executivo com decisões IA, drift e ações do dia",
    minPlan: "pro",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Command Center", route: "/dashboard/command-center" }],
    hooks: ["useAskFastCRM", "useSlashCommands", "useRecentAskQueries", "useKernelDecisions", "useKernelActions"],
    edgeFunctions: ["ask-fastcrm", "daily-revenue-brief"],
    tables: ["ask_queries"],
    features: [
      { name: "Perguntas naturais", description: "Perguntar ao sistema em linguagem natural", status: "active", aiPowered: true },
      { name: "Slash commands", description: "Comandos rápidos com /brief, /leads, etc.", status: "active", aiPowered: false },
      { name: "Command Palette", description: "Ações rápidas via ⌘K com Action Registry", status: "active", aiPowered: false },
      { name: "Kernel Decisions", description: "Ver e executar decisões pendentes do Kernel", status: "active", aiPowered: true },
      { name: "Drift Overview", description: "Visualizar drift score do workspace", status: "active", aiPowered: false },
      { name: "Ações do Dia", description: "Log de ações executadas hoje pelo Kernel", status: "active", aiPowered: false },
    ],
    dependencies: ["strategy-kernel"],
  },
  {
    id: "strategy-context-os",
    name: "Context OS",
    category: "Estratégia",
    description: "Documentação viva do negócio com 8 blocos estratégicos e IA",
    minPlan: "pro",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Context OS", route: "/dashboard/context-os" }],
    hooks: ["useContextBlocks", "useContextDependencies", "useContextBindings"],
    edgeFunctions: ["context-ai-assist", "compute-drift", "compute-impact"],
    tables: ["context_blocks", "context_block_versions", "context_dependencies", "context_drift", "context_alerts", "context_bindings"],
    features: [
      { name: "Blocos estratégicos", description: "8 tipos: Estratégia, Ofertas, Equipa, Metas, etc.", status: "active", aiPowered: false },
      { name: "AI Assist", description: "Preenchimento assistido por IA (Gemini)", status: "active", aiPowered: true },
      { name: "Context Score", description: "Percentagem de preenchimento por bloco", status: "active", aiPowered: false },
      { name: "Versionamento", description: "Histórico de versões de cada bloco", status: "active", aiPowered: false },
      { name: "Drift Score", description: "Detecção de blocos desatualizados com SLA", status: "active", aiPowered: false },
      { name: "Context Bindings", description: "Ligar blocos a assets CRM (landing, campaigns, etc.)", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "strategy-impact-map",
    name: "Mapa de Impacto",
    category: "Estratégia",
    description: "Visualização de dependências entre blocos e entidades com simulação",
    minPlan: "pro",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Impact Map", route: "/dashboard/impact-map" }],
    hooks: ["useImpactMapData", "useKernelEntities", "useKernelLinks", "useChangeEvents"],
    edgeFunctions: ["compute-impact", "kernel-compute-impact"],
    tables: ["context_dependencies", "kernel_links", "change_events", "impact_map"],
    features: [
      { name: "Grafo visual", description: "Visualizar dependências com ReactFlow/xyflow", status: "active", aiPowered: false },
      { name: "Simulação de impacto", description: "Duplo clique para simular propagação de mudanças", status: "active", aiPowered: false },
      { name: "Vista Context", description: "Mostrar blocos Context OS e suas dependências", status: "active", aiPowered: false },
      { name: "Vista Kernel", description: "Mostrar entidades cross-module e links do Kernel", status: "active", aiPowered: false },
      { name: "Nós coloridos", description: "Verde=ok, Amarelo=stale, Vermelho=impactado", status: "active", aiPowered: false },
    ],
    dependencies: ["strategy-context-os", "strategy-kernel"],
  },
  {
    id: "strategy-kernel",
    name: "FastCRM Kernel",
    category: "Estratégia",
    description: "Motor de orquestração event-driven: Context → Decisões → Ações → Métricas",
    minPlan: "pro",
    status: "active",
    moduleSlug: null,
    pages: [],
    hooks: ["useKernelDecisions", "useKernelActions", "useKernelEntities", "useDriftScores", "useContextBindings", "useChangeEvents"],
    edgeFunctions: ["kernel-ingest-event", "kernel-process-events", "kernel-compute-decisions", "kernel-run-actions", "kernel-compute-impact", "kernel-compute-drift"],
    tables: ["kernel_events", "kernel_entities", "kernel_links", "kernel_actions_registry", "kernel_action_runs", "kernel_decisions", "kernel_decision_evidence", "change_events", "impact_map", "drift_scores"],
    features: [
      { name: "Event Ingestion", description: "Captura de eventos de todos os módulos com idempotência", status: "active", aiPowered: false },
      { name: "Entity Registry", description: "Registo normalizado de entidades cross-module", status: "active", aiPowered: false },
      { name: "Dependency Graph", description: "Grafo de dependências entre entidades (kernel_links)", status: "active", aiPowered: false },
      { name: "Decision Engine", description: "Gerar decisões a partir de sinais (opp parada, hot lead, deal drop)", status: "active", aiPowered: true },
      { name: "Action Runner", description: "Executar ações recomendadas (CREATE_TASK, NOTIFY, RUN_AI_AGENT_JOB)", status: "active", aiPowered: false },
      { name: "Impact Computation", description: "Calcular impacto de mudanças via BFS no grafo", status: "active", aiPowered: false },
      { name: "Drift Scoring", description: "Calcular drift a nível de asset, módulo e workspace", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "strategy-brief",
    name: "Brief Executivo",
    category: "Estratégia",
    description: "Relatório semanal IA com decisões estratégicas",
    minPlan: "pro",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Brief Executivo", route: "/dashboard/strategic-brief" }],
    hooks: ["useStrategicBrief"],
    edgeFunctions: ["strategic-intelligence-brief", "compute-strategic-decisions"],
    tables: ["strategic_briefs", "strategic_decisions"],
    features: [
      { name: "Brief semanal", description: "Relatório automático de performance", status: "active", aiPowered: true },
      { name: "Decisões", description: "Sugestões de decisões estratégicas", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "strategy-reports",
    name: "Relatórios",
    category: "Estratégia",
    description: "Relatórios de KPIs, metas, previsões e consumo",
    minPlan: "free",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Overview", route: "/dashboard/reports" },
      { name: "KPIs", route: "/dashboard/reports/kpis" },
      { name: "Metas", route: "/dashboard/reports/goals" },
      { name: "Previsões", route: "/dashboard/reports/forecast" },
      { name: "Consumo", route: "/dashboard/reports/usage" },
    ],
    hooks: ["useReports", "useKPIAnalysis", "useRevenueForecast"],
    edgeFunctions: ["compute-revenue-forecast", "ai-kpi-analysis"],
    tables: ["reports", "kpi_targets", "revenue_forecasts"],
    features: [
      { name: "Overview", description: "Visão geral do negócio", status: "active", aiPowered: false },
      { name: "KPIs", description: "Indicadores de performance detalhados", status: "active", aiPowered: false },
      { name: "Metas", description: "Definir e acompanhar metas", status: "active", aiPowered: false },
      { name: "Previsões", description: "Previsão de receita com IA", status: "active", aiPowered: true },
      { name: "Análise KPI", description: "Análise inteligente de tendências", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },

  // ══════════ VERTICAL ══════════
  {
    id: "vertical-student",
    name: "Student Journey",
    category: "Vertical",
    description: "Gestão de alunos, cursos e turmas com copilot IA",
    minPlan: "pro",
    status: "active",
    moduleSlug: null,
    pages: [
      { name: "Alunos", route: "/dashboard/students" },
      { name: "Cursos", route: "/dashboard/courses" },
      { name: "Turmas", route: "/dashboard/classes" },
      { name: "Copilot", route: "/dashboard/student-copilot" },
    ],
    hooks: ["useStudents", "useCourses", "useClasses", "useSJCopilot"],
    edgeFunctions: ["sj-copilot", "sj-course-recommendations", "sj-daily-automation"],
    tables: ["students", "courses", "classes", "enrollments"],
    features: [
      { name: "Gestão alunos", description: "Criar e acompanhar alunos", status: "active", aiPowered: false },
      { name: "Cursos", description: "Gerir cursos e conteúdo", status: "active", aiPowered: false },
      { name: "Turmas", description: "Organizar alunos em turmas", status: "active", aiPowered: false },
      { name: "Copilot", description: "Assistente IA para educação", status: "active", aiPowered: true },
      { name: "Recomendações", description: "Sugerir cursos para alunos", status: "active", aiPowered: true },
    ],
    dependencies: [],
  },
  {
    id: "vertical-credit",
    name: "Intermediação Crédito",
    category: "Vertical",
    description: "Propostas de crédito, simulador e análise IA",
    minPlan: "pro",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Crédito", route: "/dashboard/credit" }],
    hooks: ["useCreditProposals", "useCreditSimulator"],
    edgeFunctions: ["ai-credit-analysis"],
    tables: ["credit_proposals", "credit_simulations"],
    features: [
      { name: "Propostas", description: "Criar propostas de crédito", status: "active", aiPowered: false },
      { name: "Simulador", description: "Simular condições de crédito", status: "active", aiPowered: false },
      { name: "Análise IA", description: "Análise de risco com IA", status: "active", aiPowered: true },
    ],
    dependencies: ["crm-contacts"],
  },

  // ══════════ ADMIN ══════════
  {
    id: "admin-super",
    name: "Super Admin",
    category: "Admin",
    description: "Gestão global de workspaces, users, planos e billing",
    minPlan: "agency",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Super Admin", route: "/super-admin" }],
    hooks: ["useUserRole", "useWorkspaceInstances"],
    edgeFunctions: ["admin-user-management", "admin-module-margin"],
    tables: ["admin_audit_logs", "admin_settings", "admin_notifications"],
    features: [
      { name: "Workspaces", description: "Gerir todos os workspaces", status: "active", aiPowered: false },
      { name: "Utilizadores", description: "Gerir utilizadores globais", status: "active", aiPowered: false },
      { name: "Planos", description: "Configurar planos e preços", status: "active", aiPowered: false },
      { name: "Billing", description: "Gestão de pagamentos e subscrições", status: "active", aiPowered: false },
      { name: "Activity Logs", description: "Auditoria global de acções", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "admin-automations",
    name: "Automações",
    category: "Admin",
    description: "Builder de automações com regras, workflows e logs",
    minPlan: "basic",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Automações", route: "/dashboard/automations" }],
    hooks: ["useAutomations", "useWorkflows", "useWorkflowExecutions"],
    edgeFunctions: ["ai-generate-automation", "workflow-processor", "workflow-trigger", "trigger-dispatch", "flow-engine"],
    tables: ["automations", "automation_rules", "workflows", "workflow_executions", "workflow_steps"],
    features: [
      { name: "Builder", description: "Construir automações visuais", status: "active", aiPowered: false },
      { name: "Regras", description: "Definir condições e acções", status: "active", aiPowered: false },
      { name: "Gerar com IA", description: "Gerar automações com linguagem natural", status: "active", aiPowered: true },
      { name: "Execuções", description: "Monitorizar execuções e logs", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
  {
    id: "admin-integrations",
    name: "Integrações",
    category: "Admin",
    description: "Conexões com GHL, Instagram, WhatsApp e Stripe",
    minPlan: "basic",
    status: "active",
    moduleSlug: null,
    pages: [{ name: "Integrações", route: "/dashboard/integrations" }],
    hooks: ["useIntegrations"],
    edgeFunctions: ["ghl-sync-contacts", "ghl-sync-conversations", "instagram-oauth-callback", "whatsapp-webhook"],
    tables: ["integrations", "integration_logs"],
    features: [
      { name: "GoHighLevel", description: "Sincronizar contactos e conversas", status: "active", aiPowered: false },
      { name: "Instagram", description: "Conexão OAuth com Instagram", status: "active", aiPowered: false },
      { name: "WhatsApp", description: "Receber e enviar mensagens", status: "active", aiPowered: false },
      { name: "Stripe", description: "Pagamentos e subscrições", status: "active", aiPowered: false },
    ],
    dependencies: [],
  },
];
