/**
 * LiveKit configuration
 * 
 * The LiveKit WebSocket URL is a public endpoint (like a website URL).
 * It does NOT contain any secrets — authentication is handled via tokens
 * generated by the generate-livekit-token edge function.
 * 
 * Update this value with your LiveKit Cloud project URL.
 * Format: wss://<your-project>.livekit.cloud
 */
export const LIVEKIT_SERVER_URL = "wss://fastcrm-nj06nih1.livekit.cloud";
