import {
  LayoutDashboard,
  Box,
  Inbox,
  Sparkles,
  Zap,
  Brain,
  TrendingUp,
  BarChart3,
  Layers,
  Settings,
  FileText,
  Newspaper,
  Presentation,
  Receipt,
  Store,
  ShoppingCart,
  Trophy,
} from "lucide-react";

export const NAV_V2_ITEMS = [
  { name: "Home", href: "/dashboard", icon: LayoutDashboard, end: true },
  { name: "Mural", href: "/dashboard/feed", icon: Newspaper },
  { name: "Objects", href: "/objects", icon: Box, featureFlag: "objects" },
  { name: "Inbox", href: "/dashboard/inbox", icon: Inbox },
  { name: "Ask", href: "/dashboard/ask", icon: Sparkles },
  { name: "Automations", href: "/dashboard/automations", icon: Zap },
  { name: "Intelligence", href: "/dashboard/intelligence", icon: Brain, featureFlag: "intelligence" },
  { name: "Revenue", href: "/dashboard/revenue", icon: TrendingUp },
  { name: "Propostas", href: "/dashboard/proposals", icon: Presentation },
  { name: "Faturas", href: "/dashboard/invoices", icon: Receipt },
  { name: "Portal B2B", href: "/dashboard/order-notes", icon: FileText },
  { name: "Aprovações", href: "/dashboard/order-approvals", icon: FileText },
  { name: "Loja Online", href: "/dashboard/store-products", icon: Store },
  { name: "Marketplace C2C", href: "/dashboard/c2c", icon: ShoppingCart },
  { name: "FastClub", href: "/club/fastclub", icon: Trophy },
  { name: "Reports", href: "/dashboard/reports", icon: BarChart3 },
  { name: "Strategy", href: "/dashboard/strategy", icon: Brain },
  { name: "Marketplace", href: "/dashboard/marketplace", icon: Layers, featureFlag: "marketplace" },
  { name: "Settings", href: "/settings", icon: Settings },
] as const;
