/**
 * Legacy routes that remain routable but are hidden from the v2 sidebar.
 * Used by GlobalSearch / command palette to index all accessible pages.
 */
export const LEGACY_ROUTES = [
  { path: "/dashboard/tasks", label: "Tarefas", hidden: true },
  { path: "/dashboard/leads", label: "Leads", hidden: true },
  { path: "/dashboard/contacts", label: "Contactos", hidden: true },
  { path: "/dashboard/companies", label: "Empresas", hidden: true },
  { path: "/dashboard/opportunities", label: "Oportunidades", hidden: true },
  { path: "/dashboard/proposals", label: "Propostas", hidden: true },
  { path: "/dashboard/products", label: "Produtos", hidden: true },
  { path: "/dashboard/packages", label: "Pacotes", hidden: true },
  { path: "/dashboard/payments", label: "Pagamentos", hidden: true },
  { path: "/dashboard/invoices", label: "Faturas", hidden: true },
  { path: "/dashboard/imports", label: "Importação", hidden: true },
  { path: "/dashboard/crm", label: "CRM", hidden: true },
  { path: "/dashboard/funnels", label: "Funis", hidden: true },
  { path: "/dashboard/bio", label: "Bio OS", hidden: true },
  { path: "/dashboard/form-studio", label: "Form Studio", hidden: true },
  { path: "/dashboard/ai-assistants", label: "Assistentes IA", hidden: true },
  { path: "/dashboard/ai-employees", label: "Empregados IA", hidden: true },
  { path: "/dashboard/conversational-engine", label: "Motor Conversacional", hidden: true },
  { path: "/dashboard/ai-suggestions", label: "Sugestões IA", hidden: true },
  { path: "/dashboard/kpis", label: "KPIs", hidden: true },
  { path: "/dashboard/scheduling", label: "Agendamento", hidden: true },
  { path: "/dashboard/feed", label: "Feed", hidden: true },
  { path: "/dashboard/productivity", label: "Produtividade", hidden: true },
  { path: "/dashboard/member", label: "Painel Membro", hidden: true },
  { path: "/dashboard/profile", label: "Perfil", hidden: true },
  { path: "/dashboard/marketing", label: "Marketing", hidden: true },
  { path: "/dashboard/seo", label: "SEO", hidden: true },
  { path: "/dashboard/instagram-looter", label: "Instagram Looter", hidden: true },
  { path: "/dashboard/credit", label: "Crédito", hidden: true },
  { path: "/dashboard/strategy", label: "Estratégia", hidden: true },
  { path: "/dashboard/lead-enricher", label: "Lead Enricher", hidden: true },
  { path: "/dashboard/communication/templates", label: "Templates Comunicação", hidden: true },
  { path: "/dashboard/order-notes", label: "Notas Encomenda", hidden: true },
  { path: "/dashboard/order-approvals", label: "Aprovações", hidden: true },
  { path: "/dashboard/client-users", label: "Utilizadores Cliente", hidden: true },
  { path: "/dashboard/b2b-portal", label: "Portal B2B", hidden: true },
  { path: "/dashboard/store-orders", label: "Encomendas Loja", hidden: true },
  { path: "/dashboard/store-products", label: "Produtos Loja", hidden: true },
  { path: "/dashboard/store-categories", label: "Categorias Loja", hidden: true },
  { path: "/dashboard/store-coupons", label: "Cupões Loja", hidden: true },
  { path: "/dashboard/store-analytics", label: "Analytics Loja", hidden: true },
  { path: "/dashboard/store-settings", label: "Definições Loja", hidden: true },
  { path: "/dashboard/c2c", label: "C2C Marketplace", hidden: true },
  { path: "/dashboard/fastmatch", label: "FastMatch", hidden: true },
  { path: "/dashboard/student-journey", label: "Student Journey", hidden: true },
  { path: "/dashboard/prospecting/google-local", label: "Google Local Prospecting", hidden: true },
  { path: "/dashboard/prospecting/web-search", label: "Web Search Prospecting", hidden: true },
  { path: "/dashboard/prospecting/professionals", label: "Professional Prospecting", hidden: true },
] as const;
