// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-workspaces.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/supabaseClient.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "N\xE3o autenticado." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/list-workspaces.ts
var list_workspaces_default = defineTool({
  name: "list_workspaces",
  title: "Listar workspaces",
  description: "Lista os workspaces a que o utilizador autenticado pertence, com o respetivo papel.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("workspace_members").select("role, workspace:workspaces(id, name, slug, status)").eq("user_id", ctx.getUserId());
    if (error) return errorResult(error.message);
    return jsonResult({ workspaces: data ?? [] });
  }
});

// src/lib/mcp/tools/search-contacts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";
var search_contacts_default = defineTool2({
  name: "search_contacts",
  title: "Procurar contactos",
  description: "Procura contactos do CRM num workspace por nome, email, telefone ou NIF.",
  inputSchema: {
    workspace_id: z.string().uuid().describe("ID do workspace (ver list_workspaces)."),
    query: z.string().trim().max(120).optional().describe("Texto a procurar em nome, email ou telefone."),
    limit: z.number().int().min(1).max(50).default(20).describe("N\xFAmero m\xE1ximo de resultados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("contacts").select("id, name, email, phone, company, job_title, tax_id, lifecycle_stage, total_revenue, last_contact_at").eq("workspace_id", workspace_id).is("deleted_at", null).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (query) {
      const safe = query.replace(/[,%()]/g, " ");
      q = q.or(`name.ilike.%${safe}%,email.ilike.%${safe}%,phone.ilike.%${safe}%,tax_id.ilike.%${safe}%`);
    }
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, contacts: data ?? [] });
  }
});

// src/lib/mcp/tools/search-companies.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var search_companies_default = defineTool3({
  name: "search_companies",
  title: "Procurar empresas",
  description: "Procura empresas/clientes do CRM num workspace por nome, NIF, email ou website.",
  inputSchema: {
    workspace_id: z2.string().uuid().describe("ID do workspace (ver list_workspaces)."),
    query: z2.string().trim().max(120).optional().describe("Texto a procurar em nome, NIF ou email."),
    limit: z2.number().int().min(1).max(50).default(20).describe("N\xFAmero m\xE1ximo de resultados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("companies").select("id, name, legal_name, tax_id, email, phone, website, city, abc_category, total_revenue, last_purchase_date").eq("workspace_id", workspace_id).is("deleted_at", null).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (query) {
      const safe = query.replace(/[,%()]/g, " ");
      q = q.or(`name.ilike.%${safe}%,legal_name.ilike.%${safe}%,tax_id.ilike.%${safe}%,email.ilike.%${safe}%`);
    }
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, companies: data ?? [] });
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_leads_default = defineTool4({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista as leads mais recentes de um workspace, com filtro opcional por estado.",
  inputSchema: {
    workspace_id: z3.string().uuid().describe("ID do workspace (ver list_workspaces)."),
    status: z3.string().trim().max(40).optional().describe("Estado da lead (ex.: new, qualified)."),
    limit: z3.number().int().min(1).max(50).default(20).describe("N\xFAmero m\xE1ximo de resultados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("leads").select("id, name, email, phone, company_name, source, status, lead_score, estimated_value, created_at").eq("workspace_id", workspace_id).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, leads: data ?? [] });
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var create_lead_default = defineTool5({
  name: "create_lead",
  title: "Criar lead",
  description: "Cria uma nova lead no CRM para um workspace do utilizador autenticado.",
  inputSchema: {
    workspace_id: z4.string().uuid().describe("ID do workspace (ver list_workspaces)."),
    name: z4.string().trim().min(1).max(160).describe("Nome da lead."),
    email: z4.string().trim().email().max(160).optional().describe("Email de contacto."),
    phone: z4.string().trim().max(40).optional().describe("Telefone de contacto."),
    company_name: z4.string().trim().max(160).optional().describe("Empresa associada."),
    source: z4.string().trim().max(60).optional().describe("Origem da lead (ex.: website, referral)."),
    notes: z4.string().trim().max(2e3).optional().describe("Notas iniciais.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").insert({
      workspace_id: input.workspace_id,
      name: input.name,
      email: input.email ?? null,
      phone: input.phone ?? null,
      company_name: input.company_name ?? null,
      source: input.source ?? "mcp",
      notes: input.notes ?? null,
      created_by: ctx.getUserId()
    }).select("id, name, email, phone, company_name, source, status, created_at").single();
    if (error) return errorResult(error.message);
    return jsonResult({ lead: data });
  }
});

// src/lib/mcp/tools/list-opportunities.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_opportunities_default = defineTool6({
  name: "list_opportunities",
  title: "Listar oportunidades",
  description: "Lista oportunidades (neg\xF3cios) de um workspace, com filtro opcional por estado.",
  inputSchema: {
    workspace_id: z5.string().uuid().describe("ID do workspace (ver list_workspaces)."),
    status: z5.string().trim().max(40).optional().describe("Estado da oportunidade (ex.: open, won, lost)."),
    limit: z5.number().int().min(1).max(50).default(20).describe("N\xFAmero m\xE1ximo de resultados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("opportunities").select("id, title, value, currency, status, probability, expected_close_date, company_id, contact_id, created_at").eq("workspace_id", workspace_id).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, opportunities: data ?? [] });
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z6 } from "npm:zod@^3.25.76";
var list_invoices_default = defineTool7({
  name: "list_invoices",
  title: "Listar faturas",
  description: "Lista faturas de um workspace, com filtros opcionais por estado, empresa e datas de emiss\xE3o.",
  inputSchema: {
    workspace_id: z6.string().uuid().describe("ID do workspace (ver list_workspaces)."),
    status: z6.string().trim().max(40).optional().describe("Estado da fatura (ex.: draft, sent, paid)."),
    company_id: z6.string().uuid().optional().describe("Filtrar por empresa/cliente."),
    issued_from: z6.string().trim().max(10).optional().describe("Data m\xEDnima de emiss\xE3o (YYYY-MM-DD)."),
    issued_to: z6.string().trim().max(10).optional().describe("Data m\xE1xima de emiss\xE3o (YYYY-MM-DD)."),
    limit: z6.number().int().min(1).max(100).default(25).describe("N\xFAmero m\xE1ximo de resultados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("invoices").select("id, invoice_number, status, document_type, client_name, issue_date, due_date, subtotal, tax_amount, total, amount_paid, currency").eq("workspace_id", input.workspace_id).order("issue_date", { ascending: false }).limit(input.limit ?? 25);
    if (input.status) q = q.eq("status", input.status);
    if (input.company_id) q = q.eq("company_id", input.company_id);
    if (input.issued_from) q = q.gte("issue_date", input.issued_from);
    if (input.issued_to) q = q.lte("issue_date", input.issued_to);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    const net = (data ?? []).reduce((s, r) => s + Number(r.subtotal ?? 0), 0);
    const gross = (data ?? []).reduce((s, r) => s + Number(r.total ?? 0), 0);
    return jsonResult({
      count: data?.length ?? 0,
      totals: { subtotal: Number(net.toFixed(2)), total: Number(gross.toFixed(2)) },
      invoices: data ?? []
    });
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z7 } from "npm:zod@^3.25.76";
var create_task_default = defineTool8({
  name: "create_task",
  title: "Criar tarefa",
  description: "Cria uma tarefa num workspace, opcionalmente associada a um contacto, empresa ou oportunidade.",
  inputSchema: {
    workspace_id: z7.string().uuid().describe("ID do workspace (ver list_workspaces)."),
    title: z7.string().trim().min(1).max(200).describe("T\xEDtulo da tarefa."),
    description: z7.string().trim().max(2e3).optional().describe("Descri\xE7\xE3o da tarefa."),
    due_at: z7.string().trim().max(40).optional().describe("Data/hora limite em ISO 8601."),
    priority: z7.enum(["low", "medium", "high"]).optional().describe("Prioridade da tarefa."),
    related_type: z7.enum(["contact", "company", "lead", "opportunity"]).optional().describe("Tipo de registo associado."),
    related_id: z7.string().uuid().optional().describe("ID do registo associado.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").insert({
      workspace_id: input.workspace_id,
      title: input.title,
      description: input.description ?? null,
      due_at: input.due_at ?? null,
      priority: input.priority ?? "medium",
      related_type: input.related_type ?? null,
      related_id: input.related_id ?? null,
      assigned_to: ctx.getUserId(),
      created_by: ctx.getUserId()
    }).select("id, title, status, priority, due_at, created_at").single();
    if (error) return errorResult(error.message);
    return jsonResult({ task: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "eumnfkccyvlyoyjchiwe";
var mcp_default = defineMcp({
  name: "fastcrm-mcp",
  title: "FastCRM",
  version: "0.1.0",
  instructions: "Ferramentas do FastCRM. Comece sempre por `list_workspaces` para obter o `workspace_id` do utilizador; todas as outras ferramentas exigem esse ID. Pode procurar contactos e empresas, listar leads, oportunidades e faturas, e criar leads e tarefas. Os dados devolvidos respeitam as permiss\xF5es do utilizador autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_workspaces_default,
    search_contacts_default,
    search_companies_default,
    list_leads_default,
    list_opportunities_default,
    list_invoices_default,
    create_lead_default,
    create_task_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
