-- Add commercial history columns to companies table
ALTER TABLE companies ADD COLUMN IF NOT EXISTS sales_2023 NUMERIC;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS sales_2024 NUMERIC;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS sales_2025 NUMERIC;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS sales_2026 NUMERIC;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS total_revenue NUMERIC DEFAULT 0;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS average_ticket NUMERIC;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS last_purchase_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS abc_category TEXT;