ALTER TABLE public.marketing_campaigns
  ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reviewed_by UUID,
  ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS approved_by UUID,
  ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
  ADD COLUMN IF NOT EXISTS test_sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS test_sent_by UUID,
  ADD COLUMN IF NOT EXISTS suppressed_count INTEGER DEFAULT 0;